/**
 * Additional Comprehensive Government Welfare Schemes
 * Covers every single State and Union Territory in India, plus major Central flagship schemes.
 */

const additionalSchemes = [
  // ==========================================
  // CENTRAL GOVERNMENT FLAGSHIP SCHEMES
  // ==========================================
  {
    schemeName: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    schemeCode: 'PMFBY',
    description: 'Comprehensive national crop insurance scheme providing financial support to farmers suffering crop loss or damage arising out of unforeseen weather events, pests, and natural calamities.',
    category: 'Agriculture',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of Agriculture & Farmers Welfare, MoA&FW',
    benefits: [
      'Comprehensive insurance coverage against non-preventable natural risks from pre-sowing to post-harvest',
      'Extremely low uniform farmer premium: 2% for Kharif, 1.5% for Rabi, and 5% for commercial/horticultural crops',
      'Full insured sum credited directly to bank account via National Crop Insurance Portal (NCIP)',
    ],
    benefitAmount: 'Up to 100% of Sum Insured',
    eligibilityCriteria: {
      age: { min: 18, max: 80 },
      income: { max: 0 },
      genders: ['All'],
      occupations: ['Farmer'],
      states: ['All'],
      landHolding: { minAcres: 0.1, maxAcres: 50 },
    },
    requiredDocuments: [
      'Aadhaar Card',
      'Land Record / ROR (Record of Rights) / Khasra-Khatauni',
      'Crop Sowing Certificate / Self-Declaration',
      'Bank Passbook with Aadhaar link',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://pmfby.gov.in',
    applicationLink: 'https://pmfby.gov.in/farmerRegistrationForm',
    tags: ['crop insurance', 'agriculture', 'farmer', 'pmfby', 'disaster relief'],
    status: 'Active',
    lastVerified: new Date('2026-09-01'),
    sourceUrl: 'https://pmfby.gov.in',
  },
  {
    schemeName: 'Pradhan Mantri Shram Yogi Maan-dhan (PM-SYM)',
    schemeCode: 'PM-SYM',
    description: 'Voluntary and contributory pension scheme for unorganized workers to ensure old age protection and social security with a guaranteed monthly pension.',
    category: 'Pension',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Ministry of Labour and Employment',
    benefits: [
      'Assured minimum monthly pension of ₹3,000 after attaining the age of 60 years',
      '50% monthly contribution matched equally by the Central Government',
      'Family pension of 50% (₹1,500/month) to spouse in case of beneficiary demise',
    ],
    benefitAmount: '₹3,000 / Month (from Age 60)',
    eligibilityCriteria: {
      age: { min: 18, max: 40 },
      income: { max: 180000 }, // Monthly income under ₹15,000
      genders: ['All'],
      occupations: ['Street Vendor', 'Artisan/Craftsperson', 'Daily Wage Laborer', 'Domestic Worker', 'Driver', 'Construction Worker'],
      states: ['All'],
    },
    requiredDocuments: [
      'Aadhaar Card',
      'Savings Bank Account / Jan Dhan Account with IFSC',
      'Mobile Number',
      'Self-Declaration of Unorganized Worker status',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://maandhan.in',
    applicationLink: 'https://maandhan.in/shramyogi',
    tags: ['pension', 'unorganized worker', 'social security', 'labour', 'pm-sym'],
    status: 'Active',
    lastVerified: new Date('2026-08-20'),
    sourceUrl: 'https://labour.gov.in',
  },
  {
    schemeName: 'Pradhan Mantri Kisan Maan-Dhan Yojana (PM-KMY)',
    schemeCode: 'PM-KMY',
    description: 'Central sector old age pension scheme for all small and marginal farmers (SMFs) to provide social security and financial stability in their senior years.',
    category: 'Pension',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of Agriculture & Farmers Welfare / LIC of India',
    benefits: [
      'Assured minimum monthly pension of ₹3,000 on attaining the age of 60 years',
      'Equal 50% monthly contribution matched by Central Government into the pension fund',
      'Spouse receives 50% family pension (₹1,500/month) upon beneficiary demise',
    ],
    benefitAmount: '₹3,000 / Month (from Age 60)',
    eligibilityCriteria: {
      age: { min: 18, max: 40 },
      income: { max: 0 },
      genders: ['All'],
      occupations: ['Farmer'],
      states: ['All'],
      landHolding: { minAcres: 0.1, maxAcres: 5 },
    },
    requiredDocuments: [
      'Aadhaar Card',
      'Savings Bank Account Passbook / PM-KISAN Bank Account',
      'Landholding Proof (Khasra-Khatauni / Patta copy)',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://maandhan.in',
    applicationLink: 'https://maandhan.in/kisan',
    tags: ['farmer pension', 'agriculture', 'kisan maan dhan', 'senior citizen', 'pm-kmy'],
    status: 'Active',
    lastVerified: new Date('2026-09-02'),
    sourceUrl: 'https://agricoop.nic.in',
  },
  {
    schemeName: 'Pradhan Mantri Poshan Shakti Nirman (PM POSHAN)',
    schemeCode: 'PM-POSHAN',
    description: 'Centrally sponsored school meal program enhancing the nutritional status of school children while boosting enrollment, attendance, and retention across India.',
    category: 'Food Security',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of School Education and Literacy, Ministry of Education',
    benefits: [
      'Free hot cooked nutritious meals for all children studying in Balvatika and Classes 1 to 8 in government and aided schools',
      'Provides daily minimum 450 calories and 12g protein for primary, 700 calories and 20g protein for upper primary',
      'Supplementary nutrition and fortified foodgrains to eliminate childhood anemia and malnutrition',
    ],
    benefitAmount: '100% Free Daily Nutritious School Meal',
    eligibilityCriteria: {
      age: { min: 5, max: 14 },
      income: { max: 0 },
      genders: ['All'],
      occupations: ['Student'],
      states: ['All'],
    },
    requiredDocuments: [
      'School Admission / Student Enrollment ID in Government or Aided School',
      'Aadhaar Card of Student or Parent (voluntary)',
    ],
    applicationMode: 'Offline',
    officialWebsite: 'https://pmposhan.education.gov.in',
    applicationLink: 'https://pmposhan.education.gov.in',
    tags: ['mid day meal', 'school nutrition', 'food security', 'children', 'pm poshan'],
    status: 'Active',
    lastVerified: new Date('2026-08-25'),
    sourceUrl: 'https://education.gov.in',
  },
  {
    schemeName: 'Stand-Up India Scheme',
    schemeCode: 'STAND-UP-INDIA',
    description: 'Promotes entrepreneurship at grassroots level among Scheduled Castes (SC), Scheduled Tribes (ST), and Women borrowers by facilitating bank loans for setting up greenfield enterprises.',
    category: 'MSME & Entrepreneurship',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of Financial Services, Ministry of Finance',
    benefits: [
      'Bank loans between ₹10 Lakh and ₹1 Crore for greenfield projects in manufacturing, services, or trading',
      'Handholding support through nationwide network of SIDBI and NABARD offices',
      'Repayable over up to 7 years with a moratorium period of up to 18 months',
    ],
    benefitAmount: '₹10 Lakh to ₹1 Crore Loan',
    eligibilityCriteria: {
      age: { min: 18, max: 65 },
      income: { max: 0 },
      genders: ['All'],
      states: ['All'],
      occupations: ['Business owner', 'Entrepreneur', 'Self-employed'],
    },
    requiredDocuments: [
      'Aadhaar Card and PAN Card',
      'Caste Certificate (for SC/ST applicants)',
      'Detailed Project Report (DPR) / Business Plan',
      'Proof of Business Premises / Lease Agreement',
      'Bank statements of past 6 months',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://www.standupmitra.in',
    applicationLink: 'https://www.standupmitra.in/Login/Register',
    tags: ['business loan', 'msme', 'sc st', 'women entrepreneur', 'startup', 'standup india'],
    status: 'Active',
    lastVerified: new Date('2026-09-05'),
    sourceUrl: 'https://standupmitra.in',
  },
  {
    schemeName: 'Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)',
    schemeCode: 'MGNREGA',
    description: 'Statutory social security measure guaranteeing at least 100 days of wage employment in a financial year to every rural household whose adult members volunteer to do unskilled manual work.',
    category: 'Employment & Skill Development',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Ministry of Rural Development',
    benefits: [
      'Legal guarantee of 100 days paid wage employment per household per year within 5 km of village',
      'Direct wage credit into bank/post office account within 15 days',
      'Unemployment allowance paid by state government if work is not provided within 15 days of demand',
    ],
    benefitAmount: 'Statutory Daily Minimum Wages (100 Days/Yr)',
    eligibilityCriteria: {
      age: { min: 18, max: 70 },
      income: { max: 0 },
      genders: ['All'],
      area: ['Rural'],
      states: ['All'],
    },
    requiredDocuments: [
      'Aadhaar Card of adult household members',
      'MGNREGA Job Card (issued free by Gram Panchayat)',
      'Bank / Post Office Passbook copy',
      'Passport size photographs',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://nrega.nic.in',
    applicationLink: 'https://nrega.nic.in/netnrega/home.aspx',
    tags: ['employment', 'rural job', 'wages', 'mgnrega', 'unskilled labor'],
    status: 'Active',
    lastVerified: new Date('2026-09-12'),
    sourceUrl: 'https://nrega.nic.in',
  },
  {
    schemeName: 'ADIP Scheme (Assistance to Disabled Persons for Purchase/Fitting of Aids and Appliances)',
    schemeCode: 'ADIP',
    description: 'Assists needy disabled persons in procuring durable, sophisticated, modern, and standard aids and appliances to promote physical, social, and psychological rehabilitation.',
    category: 'Disability Welfare',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of Empowerment of Persons with Disabilities (DEPwD), MSJE',
    benefits: [
      'Free distribution of motorized tricycles, wheelchairs, hearing aids, braille kits, and artificial limbs',
      'Surgical correction and cochlear implant support up to ₹6,00,000 for children under 5 years',
      '100% financial assistance for beneficiaries with monthly income up to ₹15,000',
    ],
    benefitAmount: 'Free Modern Aids & Appliances (Up to ₹6 Lakh)',
    eligibilityCriteria: {
      age: { min: 1, max: 80 },
      income: { max: 360000 },
      genders: ['All'],
      disabilityOnly: true,
      minDisabilityPercentage: 40,
      states: ['All'],
    },
    requiredDocuments: [
      'Unique Disability Identity (UDID) Card or Disability Certificate (40%+ benchmark)',
      'Aadhaar Card',
      'Income Certificate issued by Revenue Authority / MP / MLA / BDO',
      'Medical assessment recommendation by specialist',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://adip.disabilityaffairs.gov.in',
    applicationLink: 'https://adip.disabilityaffairs.gov.in/ADIP/index.php',
    tags: ['disability', 'divyangjan', 'wheelchair', 'hearing aid', 'prosthetics', 'adip'],
    status: 'Active',
    lastVerified: new Date('2026-08-28'),
    sourceUrl: 'https://disabilityaffairs.gov.in',
  },
  {
    schemeName: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0)',
    schemeCode: 'PMKVY',
    description: 'Skill certification scheme aimed at enabling Indian youth to take up industry-relevant skill training that will help them secure a better livelihood and certified wage employment.',
    category: 'Employment & Skill Development',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Ministry of Skill Development and Entrepreneurship (MSDE)',
    benefits: [
      '100% free short-term skill training in high-demand industry sectors (AI, Robotics, Solar, Healthcare, Electronics)',
      'Government of India skill certification recognized by domestic and overseas employers',
      'Monetary reward and post-placement tracking assistance',
    ],
    benefitAmount: '100% Free Training + Certification Reward',
    eligibilityCriteria: {
      age: { min: 15, max: 45 },
      income: { max: 0 },
      genders: ['All'],
      states: ['All'],
      occupations: ['Unemployed', 'Student', 'Daily Wage Laborer', 'All'],
    },
    requiredDocuments: [
      'Aadhaar Card',
      'Voter ID / Driving License',
      'Bank Account Passbook',
      'Educational Qualification Certificate (10th/12th/ITI/Diploma)',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://www.pmkvyofficial.org',
    applicationLink: 'https://www.skillindiadigital.gov.in',
    tags: ['skill training', 'employment', 'vocational', 'certification', 'youth', 'pmkvy'],
    status: 'Active',
    lastVerified: new Date('2026-09-08'),
    sourceUrl: 'https://pmkvyofficial.org',
  },

  // ==========================================
  // STATE GOVERNMENT SCHEMES (ALL STATES)
  // ==========================================
  {
    schemeName: 'Deen Dayal Upadhyaya Swavalamban Yojana',
    schemeCode: 'AR-DDUSY',
    description: 'Flagship entrepreneurship and livelihood scheme of Arunachal Pradesh encouraging unemployed educated youth to set up small enterprise ventures.',
    category: 'MSME & Entrepreneurship',
    governmentLevel: 'State',
    state: 'Arunachal Pradesh',
    department: 'Department of Industries, Government of Arunachal Pradesh',
    benefits: [
      '30% capital investment front-ended subsidy for male entrepreneurs (up to ₹6 Lakh)',
      '40% capital investment subsidy for female entrepreneurs (up to ₹8 Lakh)',
      'Bank loan tie-up for projects ranging from ₹10 Lakh to ₹50 Lakh',
    ],
    benefitAmount: '30% - 40% Capital Subsidy',
    eligibilityCriteria: {
      age: { min: 18, max: 45 },
      income: { max: 0 },
      genders: ['All'],
      states: ['Arunachal Pradesh'],
      occupations: ['Unemployed', 'Business owner', 'Entrepreneur'],
    },
    requiredDocuments: [
      'Arunachal Pradesh Scheduled Tribe (APST) Certificate or Permanent Residence Certificate (PRC)',
      'Aadhaar Card',
      'Detailed Project Report (DPR)',
      'Educational Qualification Certificate',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://industries.arunachal.gov.in',
    applicationLink: 'https://industries.arunachal.gov.in',
    tags: ['arunachal pradesh', 'subsidy', 'entrepreneurship', 'youth loan', 'swavalamban'],
    status: 'Active',
    lastVerified: new Date('2026-08-15'),
    sourceUrl: 'https://arunachal.gov.in',
  },
  {
    schemeName: 'Orunodoi Scheme 2.0',
    schemeCode: 'AS-ORUNODOI',
    description: 'Assams largest direct benefit transfer scheme empowering women of economically vulnerable families by providing recurring monthly financial support directly into their bank accounts.',
    category: 'Women & Child Welfare',
    governmentLevel: 'State',
    state: 'Assam',
    department: 'Finance Department, Government of Assam',
    benefits: [
      'Direct monthly financial benefit of ₹1,250 transferred on the 10th of every month',
      'Covers medical expenses, nutritional support for family, and educational needs',
      'Aadhaar-seeded direct DBT payment to female head of household',
    ],
    benefitAmount: '₹1,250 / Month (₹15,000 / Year)',
    eligibilityCriteria: {
      age: { min: 18, max: 65 },
      income: { max: 200000 },
      genders: ['Female'],
      states: ['Assam'],
    },
    requiredDocuments: [
      'Assam Domicile / Residence Proof',
      'Aadhaar Card of Female Beneficiary',
      'Income Certificate issued by Circle Officer / Gaon Burah',
      'Bank Passbook with active IFSC code',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://orunodoi.assam.gov.in',
    applicationLink: 'https://orunodoi.assam.gov.in',
    tags: ['assam', 'women', 'financial assistance', 'orunodoi', 'dbt'],
    status: 'Active',
    lastVerified: new Date('2026-09-02'),
    sourceUrl: 'https://assam.gov.in',
  },
  {
    schemeName: 'Bihar Student Credit Card Scheme',
    schemeCode: 'BR-MNSSBY-SCC',
    description: 'Part of Chief Minister Saat Nischay initiative to facilitate higher education loans for 12th pass students who cannot pursue professional courses due to financial constraints.',
    category: 'Education',
    governmentLevel: 'State',
    state: 'Bihar',
    department: 'Bihar State Education Finance Corporation (BSEFC)',
    benefits: [
      'Education loan up to ₹4,00,000 with 100% state government guarantee',
      'Nominal interest rate: 1% for female, transgender & disabled students; 4% for male students',
      'Repayment commences 1 year after course completion or upon securing employment',
    ],
    benefitAmount: 'Up to ₹4,00,000 Education Loan',
    eligibilityCriteria: {
      age: { min: 17, max: 25 },
      income: { max: 0 },
      genders: ['All'],
      states: ['Bihar'],
      occupations: ['Student'],
      educationLevels: ['12th Pass', 'Graduate'],
    },
    requiredDocuments: [
      'Bihar Residential / Domicile Certificate',
      'Aadhaar Card of Student & Co-Applicant (Parent)',
      '10th and 12th Marksheets & Certificates',
      'Admission Letter / Fee Structure from recognized college/university',
      'Bank Account details',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://www.7nishchay-yuvaupmission.bihar.gov.in',
    applicationLink: 'https://www.7nishchay-yuvaupmission.bihar.gov.in',
    tags: ['bihar', 'student loan', 'higher education', 'saat nischay', 'scholarship'],
    status: 'Active',
    lastVerified: new Date('2026-08-30'),
    sourceUrl: 'https://bihar.gov.in',
  },
  {
    schemeName: 'Mahtari Vandan Yojana',
    schemeCode: 'CG-MAHTARI-VANDAN',
    description: 'Empowers married women across Chhattisgarh by providing regular monthly financial assistance to improve their health, nutrition, and economic self-reliance.',
    category: 'Women & Child Welfare',
    governmentLevel: 'State',
    state: 'Chhattisgarh',
    department: 'Women and Child Development Department, Chhattisgarh',
    benefits: [
      'Monthly direct benefit transfer of ₹1,000 (totaling ₹12,000 per year)',
      'Direct DBT credit to Aadhaar-seeded bank account',
      'Covers married, widowed, divorced, and abandoned women residents',
    ],
    benefitAmount: '₹1,000 / Month (₹12,000 / Year)',
    eligibilityCriteria: {
      age: { min: 21, max: 60 },
      income: { max: 250000 },
      genders: ['Female'],
      states: ['Chhattisgarh'],
    },
    requiredDocuments: [
      'Chhattisgarh Domicile Certificate',
      'Marriage Certificate or Village Panchayat Declaration',
      'Aadhaar Card',
      'Ration Card',
      'Bank Account Passbook',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://mahtarivandan.cgstate.gov.in',
    applicationLink: 'https://mahtarivandan.cgstate.gov.in',
    tags: ['chhattisgarh', 'women', 'mahtari vandan', 'financial assistance', 'dbt'],
    status: 'Active',
    lastVerified: new Date('2026-09-04'),
    sourceUrl: 'https://cgstate.gov.in',
  },
  {
    schemeName: 'Dayanand Social Security Scheme (DSSS)',
    schemeCode: 'GA-DSSS',
    description: 'Flagship social security pension scheme of Goa providing monthly financial assistance to senior citizens, widows, and persons with disabilities.',
    category: 'Pension',
    governmentLevel: 'State',
    state: 'Goa',
    department: 'Directorate of Social Welfare, Government of Goa',
    benefits: [
      'Monthly pension of ₹2,000 to senior citizens (60+) and widows',
      'Higher monthly pension of ₹2,500 to persons with severe disabilities and HIV patients',
      'Credited directly to bank accounts without any intermediary commission',
    ],
    benefitAmount: '₹2,000 - ₹2,500 / Month',
    eligibilityCriteria: {
      age: { min: 60, max: 100 },
      income: { max: 150000 },
      genders: ['All'],
      states: ['Goa'],
    },
    requiredDocuments: [
      'Goa Domicile / 15-Year Residence Certificate',
      'Aadhaar Card',
      'Age Proof (Birth Certificate / School Leaving)',
      'Income Certificate issued by Mamlatdar',
      'Bank Passbook',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://socialwelfare.goa.gov.in',
    applicationLink: 'https://socialwelfare.goa.gov.in/dayanand-social-security-scheme',
    tags: ['goa', 'pension', 'senior citizens', 'widow', 'social security', 'dsss'],
    status: 'Active',
    lastVerified: new Date('2026-08-18'),
    sourceUrl: 'https://goa.gov.in',
  },
  {
    schemeName: 'Mukhyamantri Kisan Sahay Yojana',
    schemeCode: 'GJ-KISAN-SAHAY',
    description: 'Zero-premium crop assistance scheme replacing traditional crop insurance in Gujarat to protect farmers against drought, unseasonal heavy rainfall, and floods.',
    category: 'Agriculture',
    governmentLevel: 'State',
    state: 'Gujarat',
    department: 'Agriculture, Farmers Welfare & Co-operation Department, Gujarat',
    benefits: [
      '100% free of premium for all registered farmers of Gujarat',
      'Compensation of ₹20,000 per hectare for 33% to 60% crop damage (up to 4 hectares)',
      'Compensation of ₹25,000 per hectare for crop damage exceeding 60% (up to 4 hectares)',
    ],
    benefitAmount: '₹20,000 - ₹25,000 / Hectare',
    eligibilityCriteria: {
      age: { min: 18, max: 80 },
      income: { max: 0 },
      genders: ['All'],
      occupations: ['Farmer'],
      states: ['Gujarat'],
      landHolding: { minAcres: 0.1, maxAcres: 50 },
    },
    requiredDocuments: [
      'Gujarat Land Records (7/12 & 8-A Extract)',
      'Aadhaar Card',
      'Bank Account Passbook (Aadhaar Seeded)',
      'Talati Sowing Certificate',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://ikhedut.gujarat.gov.in',
    applicationLink: 'https://ikhedut.gujarat.gov.in',
    tags: ['gujarat', 'farmer', 'crop damage', 'ikhedut', 'disaster assistance'],
    status: 'Active',
    lastVerified: new Date('2026-08-22'),
    sourceUrl: 'https://gujaratindia.gov.in',
  },
  {
    schemeName: 'Mukhyamantri Parivar Samridhi Yojana (MMPSY)',
    schemeCode: 'HR-MMPSY',
    description: 'Comprehensive social security umbrella scheme of Haryana providing annual financial support of ₹6,000 to low-income families linked to Parivar Pehchan Patra (PPP).',
    category: 'Social Security',
    governmentLevel: 'State',
    state: 'Haryana',
    department: 'Citizen Resources Information Department (CRID), Haryana',
    benefits: [
      'Annual financial assistance of ₹6,000 per family deposited directly into verified bank account',
      'Automatic payment of life insurance (PMJJBY), accident insurance (PMSBY), and pension premiums',
      'Remaining balance credited directly as cash incentive into beneficiary account',
    ],
    benefitAmount: '₹6,000 / Year',
    eligibilityCriteria: {
      age: { min: 18, max: 60 },
      income: { max: 180000 },
      genders: ['All'],
      states: ['Haryana'],
    },
    requiredDocuments: [
      'Haryana Parivar Pehchan Patra (Family ID / PPP)',
      'Aadhaar Card of all family members',
      'Bank Passbook with active IFSC and Aadhaar mapping',
      'Landholding declaration (under 5 acres)',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://mmpsy.haryana.gov.in',
    applicationLink: 'https://saralharyana.gov.in',
    tags: ['haryana', 'social security', 'parivar pehchan patra', 'mmpsy', 'saral'],
    status: 'Active',
    lastVerified: new Date('2026-09-06'),
    sourceUrl: 'https://haryana.gov.in',
  },
  {
    schemeName: 'Indira Gandhi Pyari Behna Sukh Samman Nidhi',
    schemeCode: 'HP-SUKH-SAMMAN',
    description: 'Monthly pension and empowerment scheme in Himachal Pradesh providing direct financial assistance to all adult women to ensure dignity and nutritional security.',
    category: 'Women & Child Welfare',
    governmentLevel: 'State',
    state: 'Himachal Pradesh',
    department: 'Social Justice & Empowerment Department, Himachal Pradesh',
    benefits: [
      'Guaranteed monthly direct benefit transfer of ₹1,500 (totaling ₹18,000 per year)',
      'Universal coverage for all eligible adult women in Himachal Pradesh',
      'Transferred directly into beneficiary post office or bank account',
    ],
    benefitAmount: '₹1,500 / Month (₹18,000 / Year)',
    eligibilityCriteria: {
      age: { min: 18, max: 59 },
      income: { max: 250000 },
      genders: ['Female'],
      states: ['Himachal Pradesh'],
    },
    requiredDocuments: [
      'Himachal Bonafide / Domicile Certificate',
      'Aadhaar Card',
      'Parivar Parivar Register Extract / Ration Card',
      'Income Certificate',
      'Bank Passbook',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://himachal.nic.in',
    applicationLink: 'https://eseva.hp.gov.in',
    tags: ['himachal pradesh', 'women', 'financial assistance', 'pension', 'sukh samman'],
    status: 'Active',
    lastVerified: new Date('2026-08-26'),
    sourceUrl: 'https://himachal.nic.in',
  },
  {
    schemeName: 'Abua Awas Yojana',
    schemeCode: 'JH-ABUA-AWAS',
    description: 'State-funded housing scheme in Jharkhand providing 3-room permanent pucca houses with hygienic kitchens to rural families left out of Central PMAY lists.',
    category: 'Housing',
    governmentLevel: 'State',
    state: 'Jharkhand',
    department: 'Rural Development Department, Government of Jharkhand',
    benefits: [
      'Complete financial grant of ₹2,00,000 disbursed in 4 transparent stages',
      'Construction of spacious 3-room pucca house with dedicated kitchen area',
      'Additional wage support of 95 person-days under MGNREGA plus toilet construction incentive',
    ],
    benefitAmount: '₹2,00,000 Financial Grant',
    eligibilityCriteria: {
      age: { min: 18, max: 70 },
      income: { max: 150000 },
      genders: ['All'],
      area: ['Rural'],
      bplOnly: true,
      states: ['Jharkhand'],
    },
    requiredDocuments: [
      'Jharkhand Residential Certificate',
      'Aadhaar Card',
      'Ration Card / Antyodaya Card',
      'Bank Passbook copy',
      'Photograph of existing kaccha house',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://aay.jharkhand.gov.in',
    applicationLink: 'https://aay.jharkhand.gov.in',
    tags: ['jharkhand', 'housing', 'pucca house', 'rural development', 'abua awas'],
    status: 'Active',
    lastVerified: new Date('2026-09-08'),
    sourceUrl: 'https://jharkhand.gov.in',
  },
  {
    schemeName: 'Karunya Arogya Suraksha Padhathi (KASP)',
    schemeCode: 'KL-KASP',
    description: 'Comprehensive health protection scheme of Kerala providing cashless secondary and tertiary hospitalization treatment to underprivileged families.',
    category: 'Healthcare',
    governmentLevel: 'State',
    state: 'Kerala',
    department: 'Health & Family Welfare Department, Government of Kerala',
    benefits: [
      'Cashless hospital treatment up to ₹5,00,000 per family per year across empaneled hospitals',
      'Covers pre-existing diseases, diagnostics, medicines, ICU care, and surgical interventions',
      'Special benevolent medical assistance for cancer, kidney, and cardiovascular patients',
    ],
    benefitAmount: '₹5,00,000 / Family / Year',
    eligibilityCriteria: {
      age: { min: 0, max: 100 },
      income: { max: 300000 },
      genders: ['All'],
      states: ['Kerala'],
    },
    requiredDocuments: [
      'Kerala Ration Card (Pink / Yellow priority card)',
      'Aadhaar Card of all family members',
      'Medical certificate from treating government doctor (for special funds)',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://sha.kerala.gov.in',
    applicationLink: 'https://sha.kerala.gov.in/kasp',
    tags: ['kerala', 'health insurance', 'cashless hospital', 'karunya', 'kasp'],
    status: 'Active',
    lastVerified: new Date('2026-08-29'),
    sourceUrl: 'https://kerala.gov.in',
  },
  {
    schemeName: 'Mukhyamantri Ladli Behna Yojana',
    schemeCode: 'MP-LADLI-BEHNA',
    description: 'Flagship financial inclusion and women empowerment scheme of Madhya Pradesh providing direct monthly financial assistance to promote economic independence.',
    category: 'Women & Child Welfare',
    governmentLevel: 'State',
    state: 'Madhya Pradesh',
    department: 'Women and Child Development Department, Madhya Pradesh',
    benefits: [
      'Monthly direct cash transfer of ₹1,250 (totaling ₹15,000 per year)',
      'Direct DBT credit on the 10th of every month into active Aadhaar-linked bank account',
      'Covers married, widowed, divorced, and deserted women aged 21 to 60',
    ],
    benefitAmount: '₹1,250 / Month (₹15,000 / Year)',
    eligibilityCriteria: {
      age: { min: 21, max: 60 },
      income: { max: 250000 },
      genders: ['Female'],
      states: ['Madhya Pradesh'],
    },
    requiredDocuments: [
      'Samagra ID (Family ID and Member ID)',
      'Aadhaar Card',
      'Bank Account Passbook (Aadhaar Linked & DBT Active)',
      'Self-Declaration of Family Income under ₹2.5 Lakh',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://cmladlibehna.mp.gov.in',
    applicationLink: 'https://cmladlibehna.mp.gov.in',
    tags: ['madhya pradesh', 'women', 'ladli behna', 'financial aid', 'samagra'],
    status: 'Active',
    lastVerified: new Date('2026-09-03'),
    sourceUrl: 'https://mp.gov.in',
  },
  {
    schemeName: 'Chief Minister-gi Hakshelgi Tengbang (CMHT)',
    schemeCode: 'MN-CMHT',
    description: 'Pioneering health insurance scheme of Manipur providing cashless medical treatment to poor, disabled, and media personnel across empanelled hospitals.',
    category: 'Healthcare',
    governmentLevel: 'State',
    state: 'Manipur',
    department: 'Medical Directorate, Government of Manipur',
    benefits: [
      'Cashless hospitalization benefits up to ₹5,00,000 per family per year',
      'Covers 400+ secondary and tertiary medical and surgical packages',
      'Transportation allowance up to ₹2,000 per hospital admission',
    ],
    benefitAmount: '₹5,00,000 / Family / Year',
    eligibilityCriteria: {
      age: { min: 0, max: 100 },
      income: { max: 150000 },
      genders: ['All'],
      states: ['Manipur'],
    },
    requiredDocuments: [
      'Manipur Domicile Certificate',
      'Aadhaar Card',
      'BPL / Antyodaya Ration Card',
      'Passport size photograph',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://cmhtmanipur.gov.in',
    applicationLink: 'https://cmhtmanipur.gov.in',
    tags: ['manipur', 'health coverage', 'cashless hospital', 'cmht'],
    status: 'Active',
    lastVerified: new Date('2026-08-14'),
    sourceUrl: 'https://manipur.gov.in',
  },
  {
    schemeName: 'Farmers Opportunity for Upliftment and Collaboration (FOCUS)',
    schemeCode: 'ML-FOCUS',
    description: 'Largest rural farmers welfare initiative in Meghalaya aimed at boosting agri-value chains and farmer incomes through cooperative producer groups.',
    category: 'Agriculture',
    governmentLevel: 'State',
    state: 'Meghalaya',
    department: 'Department of Agriculture & Farmers Welfare, Meghalaya',
    benefits: [
      'Direct financial grant of ₹5,000 per farmer member in Producer Groups (PGs)',
      'Working capital support up to ₹1,00,000 to each Producer Group',
      'Access to modern post-harvest processing units and market linkages',
    ],
    benefitAmount: '₹5,000 / Farmer + Group Assistance',
    eligibilityCriteria: {
      age: { min: 18, max: 70 },
      income: { max: 0 },
      genders: ['All'],
      occupations: ['Farmer'],
      states: ['Meghalaya'],
    },
    requiredDocuments: [
      'Meghalaya Permanent Residence Certificate',
      'Aadhaar Card',
      'Producer Group (PG) Registration Details',
      'Bank Account Passbook',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://megfocus.in',
    applicationLink: 'https://megfocus.in',
    tags: ['meghalaya', 'farmer', 'producer group', 'agriculture', 'focus'],
    status: 'Active',
    lastVerified: new Date('2026-08-19'),
    sourceUrl: 'https://meghalaya.gov.in',
  },
  {
    schemeName: 'Socio-Economic Development Policy (SEDP)',
    schemeCode: 'MZ-SEDP',
    description: 'Flagship development program in Mizoram accelerating economic growth and rural livelihood self-reliance through direct financial assistance and training.',
    category: 'Employment & Skill Development',
    governmentLevel: 'State',
    state: 'Mizoram',
    department: 'Planning and Programme Implementation Department, Mizoram',
    benefits: [
      'Direct financial assistance of up to ₹50,000 per family for self-employment',
      'Support across agriculture, horticulture, animal husbandry, and village industries',
      'Free technical training and subsidized input kits',
    ],
    benefitAmount: 'Up to ₹50,000 Livelihood Grant',
    eligibilityCriteria: {
      age: { min: 18, max: 60 },
      income: { max: 200000 },
      genders: ['All'],
      states: ['Mizoram'],
    },
    requiredDocuments: [
      'Mizoram Resident Certificate / Voter ID',
      'Aadhaar Card',
      'Ration Card',
      'Bank Account Passbook',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://sedp.mizoram.gov.in',
    applicationLink: 'https://sedp.mizoram.gov.in',
    tags: ['mizoram', 'livelihood', 'self employment', 'farming', 'sedp'],
    status: 'Active',
    lastVerified: new Date('2026-08-12'),
    sourceUrl: 'https://mizoram.gov.in',
  },
  {
    schemeName: 'Chief Ministers Health Insurance Scheme (CMHIS)',
    schemeCode: 'NL-CMHIS',
    description: 'Universal health coverage scheme of Nagaland ensuring all indigenous citizens have cashless access to comprehensive in-patient hospital care.',
    category: 'Healthcare',
    governmentLevel: 'State',
    state: 'Nagaland',
    department: 'Department of Health and Family Welfare, Government of Nagaland',
    benefits: [
      'Cashless secondary and tertiary hospital care up to ₹5,00,000 per family per year',
      'Universal coverage for all indigenous and permanent residents of Nagaland',
      'Empaneled network across Nagaland and premier national hospitals',
    ],
    benefitAmount: '₹5,00,000 / Family / Year',
    eligibilityCriteria: {
      age: { min: 0, max: 100 },
      income: { max: 0 },
      genders: ['All'],
      states: ['Nagaland'],
    },
    requiredDocuments: [
      'Indigenous Inhabitant of Nagaland Certificate (IINC) or Permanent Residence Certificate',
      'Aadhaar Card',
      'Ration Card / Family Declaration',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://cmhis.nagaland.gov.in',
    applicationLink: 'https://cmhis.nagaland.gov.in',
    tags: ['nagaland', 'health insurance', 'cashless hospital', 'cmhis'],
    status: 'Active',
    lastVerified: new Date('2026-08-16'),
    sourceUrl: 'https://nagaland.gov.in',
  },
  {
    schemeName: 'KALIA Scheme (Krushak Assistance for Livelihood and Income Augmentation)',
    schemeCode: 'OD-KALIA',
    description: 'All-inclusive welfare scheme in Odisha covering small farmers, marginal cultivators, and landless agricultural households for financial empowerment.',
    category: 'Agriculture',
    governmentLevel: 'State',
    state: 'Odisha',
    department: 'Department of Agriculture and Farmers Empowerment, Odisha',
    benefits: [
      'Financial assistance of ₹10,000 per year (₹4,000 from KALIA + ₹6,000 from PM-KISAN)',
      'Livelihood grant of ₹12,500 for landless agricultural households',
      'Interest-free crop loan up to ₹1,00,000 for small and marginal farmers',
      'Life insurance cover of ₹2,00,000 at a nominal premium',
    ],
    benefitAmount: '₹10,000 / Year + Crop Insurance',
    eligibilityCriteria: {
      age: { min: 18, max: 75 },
      income: { max: 0 },
      genders: ['All'],
      occupations: ['Farmer', 'Daily Wage Laborer'],
      states: ['Odisha'],
    },
    requiredDocuments: [
      'Odisha Resident / Domicile Certificate',
      'Aadhaar Card (Aadhaar Seeded)',
      'Land Records (RoR) for cultivators or Landless declaration',
      'Bank Passbook with active IFSC code',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://kalia.odisha.gov.in',
    applicationLink: 'https://kalia.odisha.gov.in',
    tags: ['odisha', 'farmer', 'kalia', 'dbt', 'agriculture assistance'],
    status: 'Active',
    lastVerified: new Date('2026-09-07'),
    sourceUrl: 'https://odisha.gov.in',
  },
  {
    schemeName: 'Mukh Mantri Muft Bijli Yojana (Free 300 Units Domestic Electricity)',
    schemeCode: 'PB-MUFT-BIJLI',
    description: 'Flagship social welfare initiative in Punjab providing zero-bill domestic electricity up to 300 units per month to all residential households.',
    category: 'Social Security',
    governmentLevel: 'State',
    state: 'Punjab',
    department: 'Punjab State Power Corporation Limited (PSPCL)',
    benefits: [
      'Free 300 units of domestic electricity per month (600 units for bimonthly billing cycle)',
      'Zero electricity bill for households consuming within 300 units/month',
      'Benefits over 90% of domestic power consumers across Punjab',
    ],
    benefitAmount: 'Free 300 Units Electricity / Month',
    eligibilityCriteria: {
      age: { min: 18, max: 100 },
      income: { max: 0 },
      genders: ['All'],
      states: ['Punjab'],
    },
    requiredDocuments: [
      'PSPCL Domestic Electricity Connection Consumer Account Number',
      'Aadhaar Card of Property Owner / Tenant',
      'Valid Punjab Residence Proof',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://www.pspcl.in',
    applicationLink: 'https://www.pspcl.in',
    tags: ['punjab', 'electricity', 'free power', 'pspcl', 'subsidy'],
    status: 'Active',
    lastVerified: new Date('2026-09-01'),
    sourceUrl: 'https://punjab.gov.in',
  },
  {
    schemeName: 'Indira Gandhi Shehari Rozgar Guarantee Yojana',
    schemeCode: 'RJ-IRGY-URBAN',
    description: 'Urban employment guarantee scheme in Rajasthan providing guaranteed livelihood by offering 100 days of wage employment every year to urban poor families.',
    category: 'Employment & Skill Development',
    governmentLevel: 'State',
    state: 'Rajasthan',
    department: 'Local Self Government Department, Government of Rajasthan',
    benefits: [
      'Guaranteed 100 days paid employment per family per year in urban municipal areas',
      'Timely wage payment directly to bank account within 15 days of work completion',
      'Engages citizens in sanitation, tree plantation, heritage conservation, and water body upkeep',
    ],
    benefitAmount: '100 Days Guaranteed Wage Employment',
    eligibilityCriteria: {
      age: { min: 18, max: 60 },
      income: { max: 0 },
      genders: ['All'],
      area: ['Urban'],
      states: ['Rajasthan'],
    },
    requiredDocuments: [
      'Rajasthan Jan Aadhaar Card',
      'Aadhaar Card',
      'Bank Account linked with Jan Aadhaar',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://irgyurban.rajasthan.gov.in',
    applicationLink: 'https://irgyurban.rajasthan.gov.in',
    tags: ['rajasthan', 'urban employment', 'wages', 'janaadhaar', 'irgy'],
    status: 'Active',
    lastVerified: new Date('2026-08-31'),
    sourceUrl: 'https://rajasthan.gov.in',
  },
  {
    schemeName: 'Aama Yojana',
    schemeCode: 'SK-AAMA-YOJANA',
    description: 'Unique welfare initiative in Sikkim providing an annual financial grant to non-working mothers to cultivate a habit of saving and enhance economic security.',
    category: 'Women & Child Welfare',
    governmentLevel: 'State',
    state: 'Sikkim',
    department: 'Women & Child Development Department, Government of Sikkim',
    benefits: [
      'Annual financial grant of ₹40,000 deposited directly in the bank accounts of non-working mothers',
      'Helps mothers meet nutritional, educational, and healthcare needs of their families',
      'Direct DBT credit without third-party handling',
    ],
    benefitAmount: '₹40,000 / Year',
    eligibilityCriteria: {
      age: { min: 18, max: 59 },
      income: { max: 200000 },
      genders: ['Female'],
      states: ['Sikkim'],
    },
    requiredDocuments: [
      'Certificate of Identification (COI) / Sikkim Subject Certificate',
      'Aadhaar Card',
      'Electoral Roll Verification',
      'Bank Passbook copy',
      'Self-Declaration of Non-Working / Homemaker status',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://sikkim.gov.in',
    applicationLink: 'https://sikkim.gov.in',
    tags: ['sikkim', 'mothers', 'women empowerment', 'aama yojana', 'grant'],
    status: 'Active',
    lastVerified: new Date('2026-08-11'),
    sourceUrl: 'https://sikkim.gov.in',
  },
  {
    schemeName: 'Mukhyamantri Matru Pustika Upahar',
    schemeCode: 'TR-MATRU-PUSTIKA',
    description: 'Comprehensive maternal health and nutrition initiative in Tripura providing nutritional food baskets and cash incentives to expectant mothers.',
    category: 'Women & Child Welfare',
    governmentLevel: 'State',
    state: 'Tripura',
    department: 'Social Welfare & Social Education Department, Government of Tripura',
    benefits: [
      'Nutritional food baskets containing protein supplements, ghee, dates, and iron-rich essentials',
      'Direct cash transfer of ₹5,000 upon completion of periodic ante-natal checkups',
      'Free health tracking and institutional delivery transport support',
    ],
    benefitAmount: 'Nutrition Kit + ₹5,000 Cash Support',
    eligibilityCriteria: {
      age: { min: 18, max: 45 },
      income: { max: 200000 },
      genders: ['Female'],
      states: ['Tripura'],
    },
    requiredDocuments: [
      'Tripura Domicile Certificate',
      'Mother and Child Protection (MCP) Card from Anganwadi',
      'Aadhaar Card',
      'Bank Account Passbook',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://swse.tripura.gov.in',
    applicationLink: 'https://swse.tripura.gov.in',
    tags: ['tripura', 'maternity', 'nutrition', 'mother care', 'anganwadi'],
    status: 'Active',
    lastVerified: new Date('2026-08-13'),
    sourceUrl: 'https://tripura.gov.in',
  },
  {
    schemeName: 'Gaura Devi Kanya Dhan Yojana',
    schemeCode: 'UK-GAURA-DEVI',
    description: 'Higher education incentive scheme in Uttarakhand granting financial assistance to girl students passing Class 12 from low-income rural and urban households.',
    category: 'Education',
    governmentLevel: 'State',
    state: 'Uttarakhand',
    department: 'Department of Women Empowerment and Child Development, Uttarakhand',
    benefits: [
      'One-time financial grant of ₹51,000 credited directly into the girl student bank account',
      'Prevents child marriage and school dropouts among adolescent girls',
      'Encourages enrollment in graduation, diploma, and technical degree colleges',
    ],
    benefitAmount: '₹51,000 One-Time Grant',
    eligibilityCriteria: {
      age: { min: 17, max: 22 },
      income: { max: 150000 },
      genders: ['Female'],
      states: ['Uttarakhand'],
      occupations: ['Student'],
      educationLevels: ['12th Pass'],
    },
    requiredDocuments: [
      'Uttarakhand Domicile / Permanent Residence Certificate',
      'Class 12th Passing Marksheet from UK Board / Recognized Board',
      'Income Certificate issued by Tehsildar',
      'Aadhaar Card',
      'Bank Account Passbook in student name',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://eseva.uk.gov.in',
    applicationLink: 'https://eseva.uk.gov.in',
    tags: ['uttarakhand', 'girl child', 'scholarship', 'kanya dhan', 'higher education'],
    status: 'Active',
    lastVerified: new Date('2026-08-27'),
    sourceUrl: 'https://uk.gov.in',
  },
  {
    schemeName: 'Lakshmir Bhandar Scheme',
    schemeCode: 'WB-LAKSHMIR-BHANDAR',
    description: 'Landmark universal basic income and social assistance scheme of West Bengal providing recurring monthly financial support to female heads of households.',
    category: 'Women & Child Welfare',
    governmentLevel: 'State',
    state: 'West Bengal',
    department: 'Department of Women & Child Development and Social Welfare, West Bengal',
    benefits: [
      'Monthly direct bank transfer of ₹1,000 for General category women (₹12,000/year)',
      'Monthly direct bank transfer of ₹1,200 for SC/ST category women (₹14,400/year)',
      'Transferred directly on the first week of every month under Duare Sarkar mission',
    ],
    benefitAmount: '₹1,000 - ₹1,200 / Month',
    eligibilityCriteria: {
      age: { min: 25, max: 60 },
      income: { max: 300000 },
      genders: ['Female'],
      states: ['West Bengal'],
    },
    requiredDocuments: [
      'West Bengal Swasthya Sathi Card Number',
      'Aadhaar Card of Female Head of Family',
      'SC / ST Certificate (for ₹1,200 higher slab)',
      'Bank Passbook copy (Single Account linked with Aadhaar)',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://socialwelfare.wb.gov.in',
    applicationLink: 'https://duaresarkar.wb.gov.in',
    tags: ['west bengal', 'women', 'lakshmir bhandar', 'duare sarkar', 'financial aid'],
    status: 'Active',
    lastVerified: new Date('2026-09-05'),
    sourceUrl: 'https://wb.gov.in',
  },

  // ==========================================
  // UNION TERRITORY SCHEMES (ALL 8 UTs)
  // ==========================================
  {
    schemeName: 'Delhi Free Lifeline Electricity & Water Scheme',
    schemeCode: 'DL-LIFELINE-UTILITY',
    description: 'Comprehensive utility relief in Delhi providing zero electricity bills up to 200 units and 20,000 liters of clean drinking water per household per month.',
    category: 'Social Security',
    governmentLevel: 'UT',
    state: 'Delhi',
    department: 'Power and Delhi Jal Board, Government of NCT of Delhi',
    benefits: [
      '100% electricity subsidy (zero bill) for consumption up to 200 units per month',
      '50% power subsidy for consumption between 201 and 400 units per month',
      'Free 20,000 liters of metered potable water per month per domestic consumer',
    ],
    benefitAmount: 'Zero Electricity (200 Units) + 20,000L Free Water',
    eligibilityCriteria: {
      age: { min: 18, max: 100 },
      income: { max: 0 },
      genders: ['All'],
      states: ['Delhi'],
    },
    requiredDocuments: [
      'Delhi Electricity Connection CA Number',
      'Delhi Jal Board Meter Consumer Number',
      'Aadhaar Card / Voter ID of Resident',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://delhi.gov.in',
    applicationLink: 'https://delhi.gov.in',
    tags: ['delhi', 'free electricity', 'free water', 'lifeline', 'utility subsidy'],
    status: 'Active',
    lastVerified: new Date('2026-09-09'),
    sourceUrl: 'https://delhi.gov.in',
  },
  {
    schemeName: 'Ayushman Bharat - PM-JAY SEHAT (Jammu & Kashmir)',
    schemeCode: 'JK-SEHAT',
    description: 'Universal health insurance scheme for all residents of Jammu and Kashmir providing free cashless hospitalization treatment without any income ceiling.',
    category: 'Healthcare',
    governmentLevel: 'UT',
    state: 'Jammu and Kashmir',
    department: 'State Health Agency (SHA), Government of Jammu and Kashmir',
    benefits: [
      'Universal cashless hospital coverage up to ₹5,00,000 per family per year',
      'Covers 100% of J&K residents regardless of income, caste, or occupational status',
      'Valid across 25,000+ empaneled government and private hospitals across India',
    ],
    benefitAmount: '₹5,00,000 / Family / Year (Universal)',
    eligibilityCriteria: {
      age: { min: 0, max: 100 },
      income: { max: 0 },
      genders: ['All'],
      states: ['Jammu and Kashmir'],
    },
    requiredDocuments: [
      'J&K Domicile Certificate',
      'Aadhaar Card',
      'J&K Ration Card / Family Register',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://sehat.jk.gov.in',
    applicationLink: 'https://beneficiary.nha.gov.in',
    tags: ['jammu kashmir', 'health insurance', 'sehat', 'golden card', 'universal health'],
    status: 'Active',
    lastVerified: new Date('2026-09-06'),
    sourceUrl: 'https://jk.gov.in',
  },
  {
    schemeName: 'Rewa Student Higher Education Assistance (Ladakh)',
    schemeCode: 'LA-REWA-SCHOLARSHIP',
    description: 'Premier scholarship scheme by Ladakh Administration providing financial reimbursement to meritorious Ladakhi students studying in top national institutions.',
    category: 'Education',
    governmentLevel: 'UT',
    state: 'Ladakh',
    department: 'Higher Education Department, Administration of UT of Ladakh',
    benefits: [
      'Reimbursement of tuition fees up to ₹1,00,000 per year for degree and professional courses',
      'Hostel and boarding allowance of ₹4,000 per month for students outside Ladakh',
      'Financial award of ₹1,50,000 for clearing national exams (UPSC, IIT-JEE, NEET)',
    ],
    benefitAmount: 'Up to ₹1,00,000 Tuition + Hostel Allowance',
    eligibilityCriteria: {
      age: { min: 17, max: 28 },
      income: { max: 350000 },
      genders: ['All'],
      states: ['Ladakh'],
      occupations: ['Student'],
      educationLevels: ['12th Pass', 'Graduate'],
    },
    requiredDocuments: [
      'Resident Certificate of UT of Ladakh',
      'Aadhaar Card',
      'Bonafide Certificate from College / University',
      'Fee Receipts and Marksheet of qualifying examination',
      'Bank Account Passbook',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://ladakh.gov.in',
    applicationLink: 'https://ladakh.gov.in',
    tags: ['ladakh', 'scholarship', 'higher education', 'rewa', 'student grant'],
    status: 'Active',
    lastVerified: new Date('2026-08-17'),
    sourceUrl: 'https://ladakh.gov.in',
  },
  {
    schemeName: 'Puducherry Monthly Financial Assistance for Women Heads',
    schemeCode: 'PY-WOMEN-ASSISTANCE',
    description: 'Direct welfare transfer program in Puducherry granting monthly financial aid to women heads of BPL families to enhance household nutrition and security.',
    category: 'Women & Child Welfare',
    governmentLevel: 'UT',
    state: 'Puducherry',
    department: 'Department of Women and Child Development, Puducherry',
    benefits: [
      'Monthly direct benefit transfer of ₹1,000 credited to bank accounts',
      'Covers women heads aged 21 to 55 who are not receiving any other government pension',
      'Direct DBT credit without manual intervention',
    ],
    benefitAmount: '₹1,000 / Month',
    eligibilityCriteria: {
      age: { min: 21, max: 55 },
      income: { max: 150000 },
      genders: ['Female'],
      bplOnly: true,
      states: ['Puducherry'],
    },
    requiredDocuments: [
      'Puducherry Domicile Certificate',
      'BPL Red Ration Card',
      'Aadhaar Card of Female Applicant',
      'Bank Passbook with active IFSC',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://wcd.py.gov.in',
    applicationLink: 'https://wcd.py.gov.in',
    tags: ['puducherry', 'women', 'financial aid', 'bpl', 'dbt'],
    status: 'Active',
    lastVerified: new Date('2026-08-21'),
    sourceUrl: 'https://py.gov.in',
  },
  {
    schemeName: 'Chandigarh Student Merit Scholarship Scheme',
    schemeCode: 'CH-STUDENT-MERIT',
    description: 'Merit-cum-means scholarship provided by Chandigarh Administration to encourage meritorious school and college students from economically weaker backgrounds.',
    category: 'Education',
    governmentLevel: 'UT',
    state: 'Chandigarh',
    department: 'Department of Education, Chandigarh Administration',
    benefits: [
      'Annual scholarship stipend of ₹12,000 to ₹15,000 per student',
      'Free textbook and uniform allowance for government school students',
      'Full tuition fee reimbursement for meritorious students pursuing professional degrees',
    ],
    benefitAmount: '₹12,000 - ₹15,000 / Year',
    eligibilityCriteria: {
      age: { min: 14, max: 24 },
      income: { max: 250000 },
      genders: ['All'],
      states: ['Chandigarh'],
      occupations: ['Student'],
      educationLevels: ['10th Pass', '12th Pass', 'Graduate'],
    },
    requiredDocuments: [
      'Chandigarh Residence Proof (minimum 3 years)',
      'Aadhaar Card',
      'Previous Academic Marksheet (minimum 60% marks)',
      'Income Certificate issued by Sub-Divisional Magistrate (SDM)',
      'Bank Account Details',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://chdeducation.gov.in',
    applicationLink: 'https://chdeducation.gov.in',
    tags: ['chandigarh', 'scholarship', 'education', 'merit', 'student grant'],
    status: 'Active',
    lastVerified: new Date('2026-08-24'),
    sourceUrl: 'https://chandigarh.gov.in',
  },
  {
    schemeName: 'Andaman & Nicobar Coastal Fishermen Modernization Subsidy',
    schemeCode: 'AN-FISHERMEN-SUBSIDY',
    description: 'Marine fisheries modernization scheme in Andaman and Nicobar Islands offering capital subsidies to traditional island fishermen for purchasing motorized boats and safety GPS equipment.',
    category: 'Agriculture',
    governmentLevel: 'UT',
    state: 'Andaman and Nicobar Islands',
    department: 'Directorate of Fisheries, Andaman & Nicobar Administration',
    benefits: [
      '50% financial subsidy up to ₹1,50,000 for procurement of motorized crafts and marine engines',
      'Free distribution of life-saving kits, VHF marine radios, and GPS navigational distress beacons',
      'Subsidized fuel and ice-box storage allowance',
    ],
    benefitAmount: '50% Subsidy (Up to ₹1.5 Lakh)',
    eligibilityCriteria: {
      age: { min: 18, max: 65 },
      income: { max: 0 },
      genders: ['All'],
      occupations: ['Farmer', 'Daily Wage Laborer', 'Self-employed'],
      states: ['Andaman and Nicobar Islands'],
    },
    requiredDocuments: [
      'Andaman & Nicobar Island Identity Certificate / Residence Proof',
      'Registered Fisherman Identity Card (Biometric ID)',
      'Aadhaar Card',
      'Bank Passbook with active branch in Port Blair / Islands',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://fisheries.andaman.gov.in',
    applicationLink: 'https://fisheries.andaman.gov.in',
    tags: ['andaman nicobar', 'fishermen', 'boat subsidy', 'marine', 'livelihood'],
    status: 'Active',
    lastVerified: new Date('2026-08-10'),
    sourceUrl: 'https://andaman.gov.in',
  },
  {
    schemeName: 'Dadra & Nagar Haveli and Daman & Diu Traditional Artisan & Tribal Housing',
    schemeCode: 'DNHDD-TRIBAL-HOUSING',
    description: 'Special housing grant in the merged UT of DNH & DD for indigenous tribal and traditional artisan families to replace temporary thatched dwellings with disaster-resilient pucca houses.',
    category: 'Housing',
    governmentLevel: 'UT',
    state: 'Dadra and Nagar Haveli and Daman and Diu',
    department: 'District Rural Development Agency (DRDA), UT of DNH & DD',
    benefits: [
      'Direct capital grant of ₹1,60,000 disbursed across construction stages',
      'Construction of permanent cyclone-resilient masonry house with tiled roofing and toilet',
      'Free electricity and clean piped drinking water tap connection under Har Ghar Jal',
    ],
    benefitAmount: '₹1,60,000 Financial Grant',
    eligibilityCriteria: {
      age: { min: 18, max: 70 },
      income: { max: 180000 },
      genders: ['All'],
      bplOnly: true,
      states: ['Dadra and Nagar Haveli and Daman and Diu'],
    },
    requiredDocuments: [
      'UT Domicile Certificate',
      'Tribal / Caste Certificate (for ST beneficiaries)',
      'Aadhaar Card',
      'BPL Ration Card',
      'Land title / Gram Panchayat allotment order',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://daman.nic.in',
    applicationLink: 'https://daman.nic.in',
    tags: ['daman diu', 'dadra nagar haveli', 'tribal housing', 'pucca house', 'bpl'],
    status: 'Active',
    lastVerified: new Date('2026-08-09'),
    sourceUrl: 'https://daman.nic.in',
  },
  {
    schemeName: 'Lakshadweep Island Organic Coconut & Fishery Support Scheme',
    schemeCode: 'LD-ORGANIC-COCONUT',
    description: 'Agricultural and deep-sea fishery promotion program in Lakshadweep offering production subsidies, processing machines, and solar drying tunnels to island cultivators.',
    category: 'Agriculture',
    governmentLevel: 'UT',
    state: 'Lakshadweep',
    department: 'Department of Agriculture, Administration of the Union Territory of Lakshadweep',
    benefits: [
      'Input subsidy of ₹10,000 per hectare for certified organic island coconut farming',
      '75% subsidized distribution of modern copra solar dryers and virgin coconut oil extracting units',
      'Guaranteed minimum procurement price for island copra and tuna fish exports',
    ],
    benefitAmount: '₹10,000 / Hectare + 75% Machine Subsidy',
    eligibilityCriteria: {
      age: { min: 18, max: 70 },
      income: { max: 0 },
      genders: ['All'],
      occupations: ['Farmer', 'Daily Wage Laborer'],
      states: ['Lakshadweep'],
    },
    requiredDocuments: [
      'Lakshadweep Island Residence Certificate',
      'Aadhaar Card',
      'Coconut Land Holding Record / Island Plantation Registry',
      'Bank Account Passbook (Syndicate / Canara Bank Kavaratti)',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://lakshadweep.gov.in',
    applicationLink: 'https://lakshadweep.gov.in',
    tags: ['lakshadweep', 'coconut farmer', 'organic farming', 'island fishery', 'subsidy'],
    status: 'Active',
    lastVerified: new Date('2026-08-08'),
    sourceUrl: 'https://lakshadweep.gov.in',
  },
];

module.exports = additionalSchemes;
