const statesAndDistricts = [
  {
    stateName: 'Andhra Pradesh',
    code: 'AP',
    type: 'State',
    districts: ['Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Krishna', 'Kurnool', 'Nellore', 'Prakasam', 'Srikakulam', 'Visakhapatnam', 'Vizianagaram', 'West Godavari', 'YSR Kadapa', 'NTR', 'Bapatla', 'Palnadu', 'Tirupati'],
  },
  {
    stateName: 'Arunachal Pradesh',
    code: 'AR',
    type: 'State',
    districts: ['Itanagar', 'Tawang', 'West Kameng', 'East Kameng', 'Papum Pare', 'Lower Subansiri', 'Changlang'],
  },
  {
    stateName: 'Assam',
    code: 'AS',
    type: 'State',
    districts: ['Guwahati', 'Kamrup', 'Dibrugarh', 'Silchar', 'Jorhat', 'Nagaon', 'Barpeta', 'Cachar', 'Sonitpur'],
  },
  {
    stateName: 'Bihar',
    code: 'BR',
    type: 'State',
    districts: ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Purnia', 'Darbhanga', 'Bihar Sharif', 'Arrah', 'Begusarai'],
  },
  {
    stateName: 'Chhattisgarh',
    code: 'CG',
    type: 'State',
    districts: ['Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg', 'Rajnandgaon', 'Jagdalpur', 'Ambikapur'],
  },
  {
    stateName: 'Goa',
    code: 'GA',
    type: 'State',
    districts: ['North Goa', 'South Goa'],
  },
  {
    stateName: 'Gujarat',
    code: 'GJ',
    type: 'State',
    districts: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar', 'Gandhinagar', 'Junagadh', 'Kutch'],
  },
  {
    stateName: 'Haryana',
    code: 'HR',
    type: 'State',
    districts: ['Faridabad', 'Gurugram', 'Panipat', 'Ambala', 'Yamunanagar', 'Rohtak', 'Hisar', 'Karnal', 'Sonipat'],
  },
  {
    stateName: 'Himachal Pradesh',
    code: 'HP',
    type: 'State',
    districts: ['Shimla', 'Dharamshala', 'Mandi', 'Solan', 'Kullu', 'Chamba', 'Bilaspur', 'Hamirpur', 'Una'],
  },
  {
    stateName: 'Jharkhand',
    code: 'JH',
    type: 'State',
    districts: ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar', 'Hazaribagh', 'Giridih', 'Ramgarh'],
  },
  {
    stateName: 'Karnataka',
    code: 'KA',
    type: 'State',
    districts: ['Bengaluru Urban', 'Bengaluru Rural', 'Mysuru', 'Hubballi-Dharwad', 'Mangaluru', 'Belagavi', 'Kalaburagi', 'Ballari', 'Shivamogga', 'Tumakuru'],
  },
  {
    stateName: 'Kerala',
    code: 'KL',
    type: 'State',
    districts: ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Kollam', 'Thrissur', 'Kannur', 'Alappuzha', 'Kottayam', 'Palakkad', 'Malappuram'],
  },
  {
    stateName: 'Madhya Pradesh',
    code: 'MP',
    type: 'State',
    districts: ['Bhopal', 'Indore', 'Jabalpur', 'Gwalior', 'Ujjain', 'Sagar', 'Dewas', 'Satna', 'Ratlam', 'Rewa'],
  },
  {
    stateName: 'Maharashtra',
    code: 'MH',
    type: 'State',
    districts: ['Mumbai City', 'Mumbai Suburban', 'Pune', 'Nagpur', 'Thane', 'Nashik', 'Chhatrapati Sambhajinagar', 'Solapur', 'Kolhapur', 'Amravati', 'Nanded'],
  },
  {
    stateName: 'Manipur',
    code: 'MN',
    type: 'State',
    districts: ['Imphal East', 'Imphal West', 'Bishnupur', 'Thoubal', 'Churachandpur'],
  },
  {
    stateName: 'Meghalaya',
    code: 'ML',
    type: 'State',
    districts: ['East Khasi Hills', 'West Khasi Hills', 'Ri-Bhoi', 'West Garo Hills', 'South Garo Hills'],
  },
  {
    stateName: 'Mizoram',
    code: 'MZ',
    type: 'State',
    districts: ['Aizawl', 'Lunglei', 'Champhai', 'Kolasib', 'Serchhip'],
  },
  {
    stateName: 'Nagaland',
    code: 'NL',
    type: 'State',
    districts: ['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha', 'Mon'],
  },
  {
    stateName: 'Odisha',
    code: 'OD',
    type: 'State',
    districts: ['Bhubaneswar (Khurda)', 'Cuttack', 'Rourkela (Sundargarh)', 'Berhampur (Ganjam)', 'Sambalpur', 'Puri', 'Balasore', 'Bhadrak'],
  },
  {
    stateName: 'Punjab',
    code: 'PB',
    type: 'State',
    districts: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Mohali', 'Hoshiarpur', 'Pathankot'],
  },
  {
    stateName: 'Rajasthan',
    code: 'RJ',
    type: 'State',
    districts: ['Jaipur', 'Jodhpur', 'Kota', 'Bikaner', 'Ajmer', 'Udaipur', 'Bhilwara', 'Alwar', 'Sikar'],
  },
  {
    stateName: 'Sikkim',
    code: 'SK',
    type: 'State',
    districts: ['Gangtok', 'Namchi', 'Gyalshing', 'Mangan', 'Pakyong', 'Soreng'],
  },
  {
    stateName: 'Tamil Nadu',
    code: 'TN',
    type: 'State',
    districts: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 'Tirunelveli', 'Tiruppur', 'Erode', 'Vellore', 'Thanjavur'],
  },
  {
    stateName: 'Telangana',
    code: 'TG',
    type: 'State',
    districts: ['Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam', 'Ramagundam', 'Mahabubnagar', 'Nalgonda', 'Rangareddy', 'Medchal-Malkajgiri'],
  },
  {
    stateName: 'Tripura',
    code: 'TR',
    type: 'State',
    districts: ['West Tripura', 'Sepahijala', 'Khowai', 'Gomati', 'South Tripura', 'Dhalai', 'Unakoti', 'North Tripura'],
  },
  {
    stateName: 'Uttar Pradesh',
    code: 'UP',
    type: 'State',
    districts: ['Lucknow', 'Kanpur', 'Varanasi', 'Prayagraj', 'Agra', 'Meerut', 'Ghaziabad', 'Noida (Gautam Buddha Nagar)', 'Bareilly', 'Aligarh', 'Moradabad', 'Gorakhpur'],
  },
  {
    stateName: 'Uttarakhand',
    code: 'UK',
    type: 'State',
    districts: ['Dehradun', 'Haridwar', 'Roorkee', 'Haldwani', 'Nainital', 'Rishikesh', 'Udham Singh Nagar', 'Almora'],
  },
  {
    stateName: 'West Bengal',
    code: 'WB',
    type: 'State',
    districts: ['Kolkata', 'Howrah', 'North 24 Parganas', 'South 24 Parganas', 'Hooghly', 'Purba Medinipur', 'Paschim Bardhaman', 'Siliguri (Darjeeling)', 'Murshidabad'],
  },
  {
    stateName: 'Delhi',
    code: 'DL',
    type: 'Union Territory',
    districts: ['Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'North East Delhi', 'North West Delhi', 'South Delhi', 'South East Delhi', 'South West Delhi', 'West Delhi'],
  },
  {
    stateName: 'Jammu and Kashmir',
    code: 'JK',
    type: 'Union Territory',
    districts: ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Udhampur', 'Kathua'],
  },
  {
    stateName: 'Ladakh',
    code: 'LA',
    type: 'Union Territory',
    districts: ['Leh', 'Kargil'],
  },
  {
    stateName: 'Puducherry',
    code: 'PY',
    type: 'Union Territory',
    districts: ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
  },
  {
    stateName: 'Chandigarh',
    code: 'CH',
    type: 'Union Territory',
    districts: ['Chandigarh'],
  },
  {
    stateName: 'Andaman and Nicobar Islands',
    code: 'AN',
    type: 'Union Territory',
    districts: ['South Andaman', 'North and Middle Andaman', 'Nicobar'],
  },
  {
    stateName: 'Dadra and Nagar Haveli and Daman and Diu',
    code: 'DNHDD',
    type: 'Union Territory',
    districts: ['Daman', 'Diu', 'Dadra and Nagar Haveli'],
  },
  {
    stateName: 'Lakshadweep',
    code: 'LD',
    type: 'Union Territory',
    districts: ['Kavaratti', 'Agatti', 'Amini', 'Andrott'],
  },
];

const categories = [
  { name: 'Agriculture', slug: 'agriculture', description: 'Direct income support, crop insurance, and agricultural credit for farmers.', iconName: 'Tractor' },
  { name: 'Education', slug: 'education', description: 'Scholarships, fee waivers, stipends, and educational subsidies for students.', iconName: 'GraduationCap' },
  { name: 'Healthcare', slug: 'healthcare', description: 'Free hospitalization, medical insurance, maternity benefits, and diagnostic support.', iconName: 'HeartPulse' },
  { name: 'Housing', slug: 'housing', description: 'Pucca houses, interest subsidies, and rural/urban home construction aid.', iconName: 'Home' },
  { name: 'Pension', slug: 'pension', description: 'Old age pensions, widow pensions, and guaranteed monthly retirement income.', iconName: 'Clock' },
  { name: 'Women & Child Welfare', slug: 'women-child', description: 'Maternity support, girl child education funds, free cooking gas, and safety nets.', iconName: 'Users' },
  { name: 'Employment & Skill Development', slug: 'employment-skills', description: 'Guaranteed wage employment, vocational training, apprentice stipends, and placements.', iconName: 'Briefcase' },
  { name: 'MSME & Entrepreneurship', slug: 'msme-business', description: 'Collateral-free business loans, micro-credit for street vendors, and startup subsidies.', iconName: 'Store' },
  { name: 'Disability Welfare', slug: 'disability', description: 'Assistive devices, disability pensions, reservation benefits, and skill grants.', iconName: 'Accessibility' },
  { name: 'Social Security', slug: 'social-security', description: 'Life insurance, accident cover, and comprehensive safety nets for unorganized workers.', iconName: 'ShieldCheck' },
  { name: 'Food Security', slug: 'food-security', description: 'Subsidized rations, Antyodaya food grain entitlements, and nutritional programs.', iconName: 'Utensils' },
];

const schemes = [
  // 1. PM-KISAN
  {
    schemeName: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    schemeCode: 'PM-KISAN',
    description: 'Central sector scheme with 100% funding from Government of India to provide income support to all landholding farmers families in the country.',
    category: 'Agriculture',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of Agriculture and Farmers Welfare, MoA&FW',
    benefits: [
      'Direct income support of ₹6,000 per year transferred directly to bank account',
      'Disbursed in 3 equal four-monthly installments of ₹2,000 each',
      'Aadhaar-seeded direct DBT transfer without intermediaries',
    ],
    benefitAmount: '₹6,000 / Year',
    eligibilityCriteria: {
      age: { min: 18, max: 90 },
      income: { max: 0 },
      genders: ['All'],
      states: ['All'],
      occupations: ['Farmer'],
      farmerSpecific: {
        landRequired: true,
        maxLandAcres: 0,
        farmerCategories: ['Any', 'Small', 'Marginal'],
      },
    },
    ineligibilityCriteria: [
      'Institutional landholders',
      'Farmer families holding constitutional posts or retired government officers',
      'Persons who paid income tax in the last assessment year',
      'Professionals like Doctors, Engineers, Lawyers, Chartered Accountants',
    ],
    requiredDocuments: [
      'Aadhaar Card linked with active mobile number',
      'Proof of land ownership / Land Records (RoR / Pattadar Passbook)',
      'Aadhaar-seeded active Bank Account details',
      'Valid Identity and Address proof',
    ],
    applicationProcess: [
      'Visit the official PM-KISAN portal (pmkisan.gov.in) or your local Common Service Centre (CSC).',
      'Click on "Farmer Corner" and choose "New Farmer Registration".',
      'Enter your Aadhaar number, state, and complete OTP mobile verification.',
      'Enter landholding survey number, khata number, and bank account details.',
      'Submit the application for verification by State Revenue/Agriculture officials.',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://pmkisan.gov.in',
    applicationLink: 'https://pmkisan.gov.in/RegistrationFormNew.aspx',
    helplineNumber: '155261 / 011-24300606',
    status: 'Active',
    lastUpdated: new Date('2026-08-15'),
    lastVerified: new Date('2026-09-10'),
    sourceUrl: 'https://pmkisan.gov.in',
  },

  // 2. Ayushman Bharat PM-JAY
  {
    schemeName: 'Ayushman Bharat - PMJAY (Pradhan Mantri Jan Arogya Yojana)',
    schemeCode: 'PM-JAY',
    description: 'The world’s largest health assurance scheme providing health cover of ₹5 lakhs per family per year for secondary and tertiary care hospitalization to bottom 40% poor and vulnerable population.',
    category: 'Healthcare',
    governmentLevel: 'Central',
    state: 'All',
    department: 'National Health Authority (NHA), Ministry of Health and Family Welfare',
    benefits: [
      'Cashless and paperless access to healthcare services of up to ₹5,00,000 per family per year',
      'Covers up to 3 days of pre-hospitalization and 15 days of post-hospitalization expenses',
      'Covers nearly 1,949 medical and surgical procedures across empanelled hospitals',
      'No restriction on family size, age, or gender',
    ],
    benefitAmount: '₹5,00,000 / Family / Year',
    eligibilityCriteria: {
      age: { min: 0, max: 120 },
      income: { max: 250000 },
      bplOnly: true,
      rationCardCategories: ['BPL', 'AAY', 'Antyodaya', 'White', 'PHH'],
      genders: ['All'],
      states: ['All'],
    },
    ineligibilityCriteria: [
      'Households paying income tax',
      'Households owning 3 or 4 wheel motorized vehicles or mechanized agricultural equipment',
      'Government employees or pensioners',
    ],
    requiredDocuments: [
      'Aadhaar Card of all family members',
      'Ration Card / BPL card or SECC 2011 verification letter',
      'Active mobile number',
    ],
    applicationProcess: [
      'Visit the official portal mera.pmjay.gov.in or visit any empanelled public/private hospital.',
      'Check eligibility using your mobile number, ration card number, or SECC HH ID.',
      'Contact the Ayushman Mitra at the hospital helpdesk.',
      'Complete biometric e-KYC verification and download the instant Ayushman Card (Golden Card).',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://nha.gov.in',
    applicationLink: 'https://beneficiary.nha.gov.in',
    helplineNumber: '14555 / 1800-111-565',
    status: 'Active',
    lastUpdated: new Date('2026-08-20'),
    lastVerified: new Date('2026-09-12'),
    sourceUrl: 'https://pmjay.gov.in',
  },

  // 3. PMAY - Pradhan Mantri Awas Yojana (Gramin & Urban)
  {
    schemeName: 'PMAY (Pradhan Mantri Awas Yojana - Housing for All)',
    schemeCode: 'PMAY',
    description: 'Centrally sponsored flagship mission providing all-weather pucca houses with basic amenities (water, sanitation, electricity) to homeless and households living in kutcha/dilapidated houses.',
    category: 'Housing',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Ministry of Housing and Urban Affairs (MoHUA) & Ministry of Rural Development',
    benefits: [
      'Financial assistance of ₹1.20 Lakh in plains and ₹1.30 Lakh in hilly/difficult areas for Gramin',
      'Interest subsidy of up to 6.5% on housing loans up to ₹6 Lakh for EWS/LIG families in Urban',
      'Additional assistance for toilet construction under Swachh Bharat Mission (₹12,000)',
      'Unskilled labour wages for 90-95 days under MGNREGA',
    ],
    benefitAmount: '₹1,20,000 to ₹2,67,000 Subsidy',
    eligibilityCriteria: {
      age: { min: 21, max: 70 },
      income: { max: 300000 },
      genders: ['All'],
      states: ['All'],
      housingSpecific: {
        noPuccaHouse: true,
        homelessOnly: false,
      },
    },
    ineligibilityCriteria: [
      'Beneficiary family owning a pucca house anywhere in India in any member’s name',
      'Families who have previously availed central housing assistance under any scheme',
      'Families owning motorized four-wheelers or heavy agricultural equipment',
    ],
    requiredDocuments: [
      'Aadhaar Card of all family members',
      'Income Certificate issued by competent Revenue Authority',
      'Bank Account Passbook (DBT enabled)',
      'Affidavit proving no ownership of pucca house anywhere in India',
      'Land title / Patta where house will be built (for rural)',
    ],
    applicationProcess: [
      'For Urban: Visit pmaymis.gov.in or Common Service Centre (CSC) to apply under Citizen Assessment.',
      'For Gramin: Beneficiaries are identified via Gram Sabha based on SECC 2011 and Awaas+ list.',
      'Submit Aadhaar, bank details, and undergo geo-tagging inspection of current dwelling.',
      'Funds are released in 3-4 construction stage-wise milestones directly into bank account.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://pmaymis.gov.in',
    applicationLink: 'https://pmaymis.gov.in/Open/Check_Aadhar_Existence.aspx',
    helplineNumber: '011-23063285 / 1800-11-6163',
    status: 'Active',
    lastUpdated: new Date('2026-08-01'),
    lastVerified: new Date('2026-09-05'),
    sourceUrl: 'https://pmaymis.gov.in',
  },

  // 4. Atal Pension Yojana (APY)
  {
    schemeName: 'Atal Pension Yojana (APY)',
    schemeCode: 'APY',
    description: 'Guaranteed pension scheme for all Indian citizens, with special focus on unorganized sector workers, ensuring fixed monthly pension after age 60.',
    category: 'Pension',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Pension Fund Regulatory and Development Authority (PFRDA), MoF',
    benefits: [
      'Guaranteed monthly pension of ₹1,000, ₹2,000, ₹3,000, ₹4,000, or ₹5,000 per month after age 60',
      'Same pension amount guaranteed to spouse upon demise of subscriber',
      'Entire accumulated pension corpus returned to legal nominee upon death of spouse',
    ],
    benefitAmount: '₹1,000 to ₹5,000 / Month after age 60',
    eligibilityCriteria: {
      age: { min: 18, max: 40 },
      income: { max: 0 },
      genders: ['All'],
      states: ['All'],
    },
    ineligibilityCriteria: [
      'Subscribers who are income tax payers (effective Oct 1, 2022)',
      'Subscribers aged below 18 or above 40 years at entry',
    ],
    requiredDocuments: [
      'Aadhaar Card',
      'Savings Bank Account / Post Office Savings Account with auto-debit consent',
      'Nominee details',
      'Active Mobile number',
    ],
    applicationProcess: [
      'Approach your bank branch or Post Office where you have a savings account.',
      'Fill the Atal Pension Yojana (APY) registration form or enroll online via your net-banking portal.',
      'Provide your Aadhaar number, spouse/nominee details, and choose monthly pension slab (₹1,000-₹5,000).',
      'Ensure sufficient balance in your bank account for monthly auto-debit contribution.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://www.npscra.nsdl.co.in',
    applicationLink: 'https://www.npscra.nsdl.co.in/scheme-details.php',
    helplineNumber: '1800-110-069',
    status: 'Active',
    lastUpdated: new Date('2026-08-10'),
    lastVerified: new Date('2026-09-08'),
    sourceUrl: 'https://pfrda.org.in',
  },

  // 5. PM SVANidhi
  {
    schemeName: 'PM SVANidhi (PM Street Vendor’s AtmaNirbhar Nidhi)',
    schemeCode: 'PM-SVANIDHI',
    description: 'Special micro-credit facility for urban and peri-urban street vendors to resume livelihoods disrupted by economic hardships, offering collateral-free working capital loans with interest subsidies.',
    category: 'MSME & Entrepreneurship',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Ministry of Housing and Urban Affairs (MoHUA)',
    benefits: [
      'First tranche working capital loan of up to ₹10,000 (repayable in 1 year)',
      'Second tranche enhanced loan up to ₹20,000 upon timely repayment of 1st tranche',
      'Third tranche enhanced loan up to ₹50,000 for progressive vendors',
      '7% interest subsidy credited directly to bank account on timely repayment',
      'Cashback incentive up to ₹1,200 per year on digital transactions',
    ],
    benefitAmount: '₹10,000 to ₹50,000 Collateral-free Loan',
    eligibilityCriteria: {
      age: { min: 18, max: 70 },
      income: { max: 0 },
      genders: ['All'],
      states: ['All'],
      area: ['All', 'Urban'],
      occupations: ['Street Vendor'],
      streetVendorOnly: true,
      specialCategories: ['Street vendor'],
    },
    ineligibilityCriteria: [
      'Individuals not involved in street vending in urban/semi-urban areas',
      'Willful bank defaulters with active recovery proceedings',
    ],
    requiredDocuments: [
      'Certificate of Vending (CoV) / Identity Card issued by Urban Local Body (ULB)',
      'Letter of Recommendation (LoR) from Town Vending Committee / ULB if CoV not issued',
      'Aadhaar Card and active Mobile number',
      'Bank Account passbook or statement',
    ],
    applicationProcess: [
      'Visit pmsvanidhi.mohua.gov.in or download PM SVANidhi mobile app.',
      'Check your vending survey status or apply for Letter of Recommendation (LoR).',
      'Select preferred lending institution and loan amount.',
      'Upload Aadhaar and submit application. Loan sanctioned without physical collateral.',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://pmsvanidhi.mohua.gov.in',
    applicationLink: 'https://pmsvanidhi.mohua.gov.in/Home/Vendor_register',
    helplineNumber: '1800-11-1979',
    status: 'Active',
    lastUpdated: new Date('2026-07-28'),
    lastVerified: new Date('2026-09-02'),
    sourceUrl: 'https://pmsvanidhi.mohua.gov.in',
  },

  // 6. PM Mudra Yojana
  {
    schemeName: 'PM Mudra Yojana (Pradhan Mantri MUDRA Yojana)',
    schemeCode: 'PMMY',
    description: 'Provides collateral-free loans up to ₹20 Lakhs to non-corporate, non-farm small and micro enterprises across Shishu, Kishore, and Tarun categories.',
    category: 'MSME & Entrepreneurship',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of Financial Services (DFS), Ministry of Finance',
    benefits: [
      'Shishu Category: Loans up to ₹50,000 for startup micro-units',
      'Kishore Category: Loans from ₹50,001 up to ₹5,00,000 for developing enterprises',
      'Tarun Category: Loans from ₹5,00,001 up to ₹10,00,000 (extended up to ₹20 Lakhs in 2024 budget)',
      'Zero collateral or third-party security required',
      'Affordable interest rates linked to RBI benchmark',
    ],
    benefitAmount: 'Up to ₹20,00,000 Business Loan',
    eligibilityCriteria: {
      age: { min: 18, max: 65 },
      income: { max: 0 },
      genders: ['All'],
      states: ['All'],
      occupations: ['Self-employed', 'Business owner', 'Other'],
    },
    ineligibilityCriteria: [
      'Large corporate entities or publicly listed firms',
      'Defaulters with non-performing loans in commercial or regional rural banks',
    ],
    requiredDocuments: [
      'Aadhaar Card / Voter ID / Passport',
      'Proof of Business Enterprise (Shop Act, Udyam Registration, or Trade License)',
      'Past 6 months bank statement',
      'Quotation of machinery/items to be purchased (if applicable)',
      'Recent passport-size photographs',
    ],
    applicationProcess: [
      'Formulate a viable micro-business plan for trade, service, or manufacturing.',
      'Apply online via the official Udyamimitra portal (udyamimitra.in) or visit any commercial bank/NBFC.',
      'Submit the MUDRA application form along with business registration and KYC.',
      'The bank sanctions the loan and issues a MUDRA RuPay Debit Card for working capital.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://www.mudra.org.in',
    applicationLink: 'https://www.udyamimitra.in',
    helplineNumber: '1800-180-1111 / 1800-11-0001',
    status: 'Active',
    lastUpdated: new Date('2026-08-18'),
    lastVerified: new Date('2026-09-14'),
    sourceUrl: 'https://www.mudra.org.in',
  },

  // 7. PM Ujjwala Yojana 2.0
  {
    schemeName: 'PM Ujjwala Yojana 2.0 (Pradhan Mantri Ujjwala Yojana)',
    schemeCode: 'PMUY',
    description: 'Provides deposit-free LPG gas connections to adult women from poor and underprivileged households, safeguarding health from indoor air pollution.',
    category: 'Women & Child Welfare',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Ministry of Petroleum and Natural Gas (MoPNG)',
    benefits: [
      'Deposit-free 14.2 kg or 5 kg single LPG cylinder connection',
      'Cash assistance of ₹1,600 for cylinder security deposit, regulator, and hose pipe',
      'First LPG refill and cooking stove (hotplate) provided completely free of cost',
      'Targeted subsidy of ₹300 per cylinder for up to 12 refills per year',
    ],
    benefitAmount: 'Free LPG Connection + First Refill + Stove',
    eligibilityCriteria: {
      age: { min: 18, max: 90 },
      income: { max: 200000 },
      genders: ['Female'],
      states: ['All'],
      bplOnly: true,
    },
    ineligibilityCriteria: [
      'Households that already possess an active LPG connection in any member’s name',
      'Male applicants (scheme connection is strictly issued in adult woman’s name)',
    ],
    requiredDocuments: [
      'Aadhaar Card of the adult woman applicant',
      'Ration Card / BPL card verifying family composition',
      'Bank Account details (Aadhaar linked)',
      '14-Point Declaration of no existing LPG connection',
    ],
    applicationProcess: [
      'Apply online on pmuy.gov.in or visit your nearest LPG distributor (Indane, Bharatgas, HP Gas).',
      'Submit the Ujjwala KYC application form with woman’s Aadhaar and Ration Card.',
      'Distributor verifies duplicate connection database across all OMCs.',
      'Connection installed at applicant’s residence with free hotplate and safety demonstration.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://www.pmuy.gov.in',
    applicationLink: 'https://www.pmuy.gov.in/apply-online.html',
    helplineNumber: '1800-266-6696 / 1906',
    status: 'Active',
    lastUpdated: new Date('2026-07-20'),
    lastVerified: new Date('2026-09-01'),
    sourceUrl: 'https://www.pmuy.gov.in',
  },

  // 8. PM Vishwakarma Scheme
  {
    schemeName: 'PM Vishwakarma Scheme',
    schemeCode: 'PM-VISHWAKARMA',
    description: 'Comprehensive support scheme for traditional artisans and craftspeople working with their hands and tools across 18 traditional trades.',
    category: 'Skill Development',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Ministry of Micro, Small and Medium Enterprises (MoMSME)',
    benefits: [
      'PM Vishwakarma Certificate and ID Card conferring official recognition',
      'Skill upgradation with 5-7 days basic training and ₹500/day stipend during training',
      'Toolkit incentive of ₹15,000 e-voucher for modern equipment',
      'Collateral-free credit support up to ₹1 Lakh (1st tranche) and ₹2 Lakhs (2nd tranche) at concessional 5% interest rate',
      'Incentive for digital transactions (₹1 per transaction up to 100/month)',
    ],
    benefitAmount: '₹15,000 Toolkit + ₹3 Lakh Concessional Loan',
    eligibilityCriteria: {
      age: { min: 18, max: 70 },
      income: { max: 300000 },
      genders: ['All'],
      states: ['All'],
      occupations: ['Artisan/Craftsperson', 'Handicraft worker'],
      artisanOnly: true,
      specialCategories: ['Artisan/Craftsperson'],
    },
    ineligibilityCriteria: [
      'Beneficiary or family member employed in government service',
      'Individuals who have availed similar credit schemes (PMEGP, Mudra, PM SVANidhi) without fully settling dues',
      'Only one member per family is eligible',
    ],
    requiredDocuments: [
      'Aadhaar Card',
      'Mobile number linked with Aadhaar',
      'Bank Account details',
      'Trade self-declaration in one of 18 trades (Carpenter, Blacksmith, Potter, Mason, Tailor, Cobbler, etc.)',
    ],
    applicationProcess: [
      'Visit nearest Common Service Centre (CSC) or pmvishwakarma.gov.in.',
      'Complete biometric authentication and register trade details.',
      'Application verified by Gram Panchayat / Urban Local Body and District Implementation Committee.',
      'Receive Vishwakarma digital certificate and enroll for skill training.',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://pmvishwakarma.gov.in',
    applicationLink: 'https://pmvishwakarma.gov.in/Home/Registration',
    helplineNumber: '1800-267-7777 / 011-23061500',
    status: 'Active',
    lastUpdated: new Date('2026-08-25'),
    lastVerified: new Date('2026-09-11'),
    sourceUrl: 'https://pmvishwakarma.gov.in',
  },

  // 9. PM Jeevan Jyoti Bima Yojana (PMJJBY)
  {
    schemeName: 'PM Jeevan Jyoti Bima Yojana (PMJJBY)',
    schemeCode: 'PMJJBY',
    description: 'One-year renewable life insurance scheme offering ₹2 Lakh life cover for death due to any cause at an affordable annual premium of ₹436.',
    category: 'Social Security',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of Financial Services, Ministry of Finance',
    benefits: [
      '₹2,00,000 life insurance cover payable to nominee on death of subscriber due to any reason',
      'Affordable annual premium of only ₹436 per member',
      'Auto-debit facility from subscriber’s savings bank account',
    ],
    benefitAmount: '₹2,00,000 Life Insurance Cover',
    eligibilityCriteria: {
      age: { min: 18, max: 50 },
      income: { max: 0 },
      genders: ['All'],
      states: ['All'],
    },
    ineligibilityCriteria: [
      'Individuals aged below 18 or above 50 years at enrollment',
      'Subscribers who do not maintain sufficient balance for annual auto-debit',
    ],
    requiredDocuments: [
      'Aadhaar Card',
      'Savings Bank Account with auto-debit consent',
      'Nominee details',
    ],
    applicationProcess: [
      'Enroll via net-banking / mobile banking app of your savings account bank.',
      'Or visit bank branch / Post Office and submit the PMJJBY consent-cum-declaration form.',
      'Authorize auto-debit of ₹436 annually in May.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://financialservices.gov.in',
    applicationLink: 'https://www.jansuraksha.gov.in',
    helplineNumber: '1800-180-1111 / 1800-110-001',
    status: 'Active',
    lastUpdated: new Date('2026-08-05'),
    lastVerified: new Date('2026-09-03'),
    sourceUrl: 'https://jansuraksha.gov.in',
  },

  // 10. PM Suraksha Bima Yojana (PMSBY)
  {
    schemeName: 'PM Suraksha Bima Yojana (PMSBY)',
    schemeCode: 'PMSBY',
    description: 'Affordable accident insurance scheme providing ₹2 Lakh cover for accidental death or permanent total disability at a nominal annual premium of just ₹20.',
    category: 'Social Security',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of Financial Services, Ministry of Finance',
    benefits: [
      '₹2,00,000 in case of accidental death or permanent total disability (both eyes/hands/feet)',
      '₹1,00,000 in case of permanent partial disability (one eye/hand/foot)',
      'Nominal annual premium of ₹20 auto-debited annually',
    ],
    benefitAmount: '₹2,00,000 Accidental Cover for ₹20/Year',
    eligibilityCriteria: {
      age: { min: 18, max: 70 },
      income: { max: 0 },
      genders: ['All'],
      states: ['All'],
    },
    ineligibilityCriteria: [
      'Persons below 18 or above 70 years',
      'Death or injury resulting from non-accidental causes (natural death not covered)',
    ],
    requiredDocuments: [
      'Aadhaar Card',
      'Savings Bank Account with auto-debit mandate',
      'Nominee details',
    ],
    applicationProcess: [
      'Enroll through internet banking, SMS banking, or at your local bank branch.',
      'Submit one-page enrollment form authorizing ₹20 annual deduction.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://jansuraksha.gov.in',
    applicationLink: 'https://www.jansuraksha.gov.in',
    helplineNumber: '1800-180-1111',
    status: 'Active',
    lastUpdated: new Date('2026-08-05'),
    lastVerified: new Date('2026-09-03'),
    sourceUrl: 'https://jansuraksha.gov.in',
  },

  // 11. National Means-cum-Merit Scholarship Scheme (NMMSS)
  {
    schemeName: 'National Means-cum-Merit Scholarship Scheme (NMMSS)',
    schemeCode: 'NMMSS',
    description: 'Centrally sponsored scholarship scheme to award scholarships to meritorious students of economically weaker sections to arrest dropouts at class VIII and encourage study till secondary stage.',
    category: 'Education',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of School Education & Literacy, Ministry of Education',
    benefits: [
      'Scholarship of ₹12,000 per annum (₹1,000 per month) for study from Class IX to Class XII',
      'Disbursed directly via DBT into student’s bank account through Public Financial Management System (PFMS)',
    ],
    benefitAmount: '₹12,000 / Year',
    eligibilityCriteria: {
      age: { min: 12, max: 19 },
      income: { max: 350000 },
      studentOnly: true,
      educationLevels: ['8th Pass', '10th Pass', 'All'],
      genders: ['All'],
      states: ['All'],
    },
    ineligibilityCriteria: [
      'Students studying in Kendriya Vidyalayas, Jawahar Navodaya Vidyalayas, and residential schools run by State Government',
      'Students studying in private un-aided institutions',
    ],
    requiredDocuments: [
      'Class VII / VIII mark sheet showing minimum 55% marks (50% for SC/ST)',
      'Income Certificate of parents from competent state authority (Max ₹3.5 Lakh/year)',
      'Aadhaar card of student',
      'Active Bank Account passbook in student’s name',
      'Caste certificate / Disability certificate (if applicable)',
    ],
    applicationProcess: [
      'Apply online on National Scholarship Portal (scholarships.gov.in).',
      'Appear in the state-level NMMSS selection test conducted by State/UT Education Department.',
      'Upon selection, complete NSP profile verification and Aadhaar biometric authentication.',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://scholarships.gov.in',
    applicationLink: 'https://scholarships.gov.in',
    helplineNumber: '0120-6619540',
    status: 'Active',
    lastUpdated: new Date('2026-07-15'),
    lastVerified: new Date('2026-09-07'),
    sourceUrl: 'https://dsel.education.gov.in',
  },

  // 12. Sukanya Samriddhi Yojana (SSY)
  {
    schemeName: 'Sukanya Samriddhi Yojana (SSY)',
    schemeCode: 'SSY',
    description: 'Small savings scheme under Beti Bachao Beti Padhao campaign offering attractive interest rates and triple tax exemptions (EEE) to build marriage and education fund for girl child.',
    category: 'Women & Child Welfare',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Department of Economic Affairs, Ministry of Finance',
    benefits: [
      'Highest sovereign guaranteed interest rate (8.2% p.a. compounded annually)',
      'Triple Tax exemption under Section 80C (Exempt-Exempt-Exempt)',
      'Account matures 21 years from date of opening or upon marriage after age 18',
      'Partial withdrawal up to 50% allowed for higher education after age 18',
    ],
    benefitAmount: 'High-Interest Small Savings + Tax Exemption',
    eligibilityCriteria: {
      age: { min: 0, max: 10 },
      income: { max: 0 },
      genders: ['Female'],
      states: ['All'],
    },
    ineligibilityCriteria: [
      'Girl child aged above 10 years at account opening',
      'More than 2 accounts per family (except in case of twin/triplet girl children)',
    ],
    requiredDocuments: [
      'Birth Certificate of the girl child',
      'Aadhaar Card and address proof of guardian / parent',
      'Photographs of child and guardian',
    ],
    applicationProcess: [
      'Visit any Post Office or authorized commercial bank branch.',
      'Fill Sukanya Samriddhi Account opening form with minimum opening deposit of ₹250.',
      'Submit birth certificate and guardian KYC.',
    ],
    applicationMode: 'Offline',
    officialWebsite: 'https://www.indiapost.gov.in',
    applicationLink: 'https://www.indiapost.gov.in/Financial/Pages/Content/Sukanya-Samriddhi-Account.aspx',
    helplineNumber: '1800-266-6868',
    status: 'Active',
    lastUpdated: new Date('2026-08-01'),
    lastVerified: new Date('2026-09-04'),
    sourceUrl: 'https://www.indiapost.gov.in',
  },

  // 13. Divyangjan Swavalamban Yojana
  {
    schemeName: 'Divyangjan Swavalamban Yojana',
    schemeCode: 'DSY-PWD',
    description: 'Concessional credit scheme for Persons with Disabilities (PwDs) to promote self-employment, vocational trade, and economic empowerment.',
    category: 'Disability Welfare',
    governmentLevel: 'Central',
    state: 'All',
    department: 'National Handicapped Finance and Development Corporation (NHFDC), DEPwD',
    benefits: [
      'Concessional loans up to ₹50 Lakhs for business projects and self-employment ventures',
      'Subsidized interest rate with additional 0.5% - 1% rebate for women with disabilities',
      'Financial assistance for purchasing assistive aids, vehicles, and custom equipment',
    ],
    benefitAmount: 'Up to ₹50,00,000 Low-interest Credit',
    eligibilityCriteria: {
      age: { min: 18, max: 65 },
      income: { max: 500000 },
      disabilityOnly: true,
      minDisabilityPercentage: 40,
      genders: ['All'],
      states: ['All'],
    },
    ineligibilityCriteria: [
      'Disability less than 40% benchmark',
      'Persons aged below 18 years',
    ],
    requiredDocuments: [
      'Unique Disability ID (UDID) Card or Medical Board Certificate (min 40%)',
      'Aadhaar Card',
      'Educational / Technical qualification certificates',
      'Project proposal for self-employment business',
      'Bank Account Passbook',
    ],
    applicationProcess: [
      'Apply online through NHFDC portal or State Channelising Agencies (SCAs).',
      'Submit business project proposal along with UDID certificate.',
      'Approved credit is disbursed through designated nationalized or regional rural banks.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://nhfdc.nic.in',
    applicationLink: 'https://nhfdc.nic.in',
    helplineNumber: '0129-2226910',
    status: 'Active',
    lastUpdated: new Date('2026-07-22'),
    lastVerified: new Date('2026-09-06'),
    sourceUrl: 'https://nhfdc.nic.in',
  },

  // 14. Indira Gandhi National Old Age Pension Scheme (IGNOAPS)
  {
    schemeName: 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)',
    schemeCode: 'IGNOAPS',
    description: 'Non-contributory monthly pension provided under the National Social Assistance Programme (NSAP) to destitute senior citizens living below poverty line.',
    category: 'Pension',
    governmentLevel: 'Central',
    state: 'All',
    department: 'Ministry of Rural Development (MoRD)',
    benefits: [
      'Monthly pension to destitute senior citizens (supplemented by additional state contribution)',
      'Higher pension amount for super senior citizens aged 80 years and above',
      'Direct credit into beneficiary bank/post office account through DBT',
    ],
    benefitAmount: 'Monthly Senior Citizen Pension',
    eligibilityCriteria: {
      age: { min: 60, max: 120 },
      income: { max: 100000 },
      bplOnly: true,
      seniorCitizenOnly: true,
      genders: ['All'],
      states: ['All'],
    },
    ineligibilityCriteria: [
      'Citizens having regular source of independent income or receiving other government pensions',
      'Citizens living with gainfully employed adult children having sufficient income',
    ],
    requiredDocuments: [
      'Aadhaar Card or Age proof certificate',
      'BPL Ration Card / Inclusion in SECC BPL list',
      'Bank Passbook or Post Office Savings Account passbook',
      'Passport size photographs',
    ],
    applicationProcess: [
      'Submit application at local Block Development Office (BDO), Municipal Office, or Gram Panchayat.',
      'Or apply online on nsap.nic.in.',
      'Field inquiry and sanction by District Social Welfare Committee.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://nsap.nic.in',
    applicationLink: 'https://nsap.nic.in',
    helplineNumber: '1800-111-555',
    status: 'Active',
    lastUpdated: new Date('2026-08-12'),
    lastVerified: new Date('2026-09-08'),
    sourceUrl: 'https://nsap.nic.in',
  },

  // ----------------------------------------------------
  // STATE SCHEMES - ANDHRA PRADESH (Featured strongly)
  // ----------------------------------------------------

  // 15. AP - Thalliki Vandanam
  {
    schemeName: 'Thalliki Vandanam Scheme (Andhra Pradesh)',
    schemeCode: 'AP-THALLIKI-VANDANAM',
    description: 'Flagship education welfare scheme of Government of Andhra Pradesh providing financial assistance of ₹15,000 per child per year to mothers of eligible school-going children to ensure 100% literacy and prevent school dropouts.',
    category: 'Education',
    governmentLevel: 'State',
    state: 'Andhra Pradesh',
    department: 'School Education Department, Government of Andhra Pradesh',
    benefits: [
      'Financial assistance of ₹15,000 per annum credited directly into the mother’s bank account for every school-going child',
      'Covers children studying from Class 1 to Intermediate (Class 12) across government and recognized private schools',
      'Encourages regular attendance (minimum 75% attendance mandatory)',
    ],
    benefitAmount: '₹15,000 / Child / Year',
    eligibilityCriteria: {
      age: { min: 5, max: 20 },
      income: { max: 250000 },
      studentOnly: true,
      states: ['Andhra Pradesh'],
      genders: ['All'],
      rationCardCategories: ['White', 'BPL', 'Antyodaya', 'Any'],
    },
    ineligibilityCriteria: [
      'Families of government employees or income tax payers',
      'Children with school attendance less than 75%',
      'Families owning more than 10 acres of wetland or 25 acres of dryland',
      'Residents of states other than Andhra Pradesh',
    ],
    requiredDocuments: [
      'Aadhaar Cards of child and mother',
      'Rice Card / White Ration Card of Andhra Pradesh',
      'Child Study Certificate / U-DISE student code from school',
      'Mother’s active Bank Passbook (NPCI linked for DBT)',
      'Electricity consumption proof (under 300 units/month)',
    ],
    applicationProcess: [
      'Schools collect student data and upload it to the Child Info / Jnanabhumi education portal.',
      'Headmaster verifies student attendance (≥ 75%) and mother’s bank details.',
      'Village/Ward Sachivalayam (GSWS) conducts social audit and field verification.',
      'Sanctioned amount is transferred directly to mother’s bank account on designated DBT release day.',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://jnanabhumi.ap.gov.in',
    applicationLink: 'https://jnanabhumi.ap.gov.in',
    helplineNumber: '1902 (AP GSWS Toll-free)',
    status: 'Active',
    lastUpdated: new Date('2026-08-30'),
    lastVerified: new Date('2026-09-15'),
    sourceUrl: 'https://jnanabhumi.ap.gov.in',
  },

  // 16. AP - NTR Bharosa Pension Scheme (Social Security)
  {
    schemeName: 'NTR Bharosa Pension Scheme (Andhra Pradesh Social Security Pension)',
    schemeCode: 'AP-NTR-BHAROSA',
    description: 'Enhanced monthly social security pension scheme providing dignified financial support to vulnerable senior citizens, widows, weavers, toddy tappers, and persons with disabilities across Andhra Pradesh.',
    category: 'Pension',
    governmentLevel: 'State',
    state: 'Andhra Pradesh',
    department: 'Society for Elimination of Rural Poverty (SERP), PR & RD Department, AP',
    benefits: [
      'Enhanced monthly pension of ₹4,000 for Senior Citizens, Widows, Weavers, and Single Women',
      'Enhanced monthly pension of ₹6,000 for Persons with Benchmark Disabilities (40% to 79%)',
      'Enhanced monthly pension of ₹15,000 for Persons with Severe Disabilities (≥ 80%) and chronic kidney patients',
      'Doorstep delivery of cash pension on 1st of every month through Village/Ward Secretariat volunteers',
    ],
    benefitAmount: '₹4,000 to ₹15,000 / Month',
    eligibilityCriteria: {
      age: { min: 18, max: 120 },
      income: { max: 120000 },
      states: ['Andhra Pradesh'],
      genders: ['All'],
      bplOnly: true,
      rationCardCategories: ['White', 'BPL', 'Antyodaya'],
    },
    ineligibilityCriteria: [
      'Families having any active government employee or pensioner',
      'Families owning four-wheeler motor vehicles (excluding taxi/tractor/auto)',
      'Monthly electricity consumption exceeding 300 units in rural or urban',
    ],
    requiredDocuments: [
      'Aadhaar Card of the applicant',
      'Andhra Pradesh Rice Card (White Ration Card)',
      'SADAREM Disability Certificate (for disability pension applicants)',
      'Death certificate of husband (for widow pension applicants)',
      'Age proof / Voter ID / Birth Certificate',
    ],
    applicationProcess: [
      'Submit application form at your local Village Secretariat (Grama Sachivalayam) or Ward Secretariat.',
      'Welfare & Education Assistant verifies eligibility criteria and documents.',
      'Social audit list published at Secretariat notice board.',
      'Upon sanction by District Collector, pension card is issued with doorstep monthly disbursement.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://sspensions.ap.gov.in',
    applicationLink: 'https://gramawardsachivalayam.ap.gov.in',
    helplineNumber: '1902 / 0866-2410017',
    status: 'Active',
    lastUpdated: new Date('2026-08-28'),
    lastVerified: new Date('2026-09-14'),
    sourceUrl: 'https://sspensions.ap.gov.in',
  },

  // 17. AP - Rythu Bharosa / Annadata Sukhibhava
  {
    schemeName: 'Annadata Sukhibhava - Rythu Bharosa (Andhra Pradesh)',
    schemeCode: 'AP-ANNADATA-BHAROSA',
    description: 'Comprehensive farmer financial support scheme of Andhra Pradesh combining state financial assistance with Central PM-KISAN to support agricultural input investments for landowner and tenant farmers.',
    category: 'Agriculture',
    governmentLevel: 'State',
    state: 'Andhra Pradesh',
    department: 'Department of Agriculture, Government of Andhra Pradesh',
    benefits: [
      'Enhanced annual input subsidy of up to ₹20,000 per farmer family per year (incorporating state component and PM-KISAN)',
      'Includes tenant farmers (CCRC cardholders) belonging to SC, ST, BC, and Minority communities',
      'Free crop insurance (YSR Free Crop Insurance) and interest-free crop loans (Sunna Vaddi Panta Runalu)',
    ],
    benefitAmount: 'Up to ₹20,000 / Year',
    eligibilityCriteria: {
      age: { min: 18, max: 90 },
      income: { max: 0 },
      states: ['Andhra Pradesh'],
      occupations: ['Farmer'],
      farmerSpecific: {
        landRequired: true,
        maxLandAcres: 0,
        farmerCategories: ['Any', 'Small', 'Marginal'],
      },
    },
    ineligibilityCriteria: [
      'Persons holding constitutional posts, sitting MPs/MLAs, or retired government staff',
      'Income tax payers',
    ],
    requiredDocuments: [
      'Aadhaar Card',
      'Pattadar Passbook / 1-B Adangal / Webland revenue record',
      'Crop Cultivator Rights Card (CCRC) for tenant farmers',
      'Aadhaar-seeded Bank Account passbook',
    ],
    applicationProcess: [
      'Visit your local Rythu Bharosa Kendra (RBK) at the village level.',
      'Agriculture Assistant verifies Webland adangal and e-Crop booking details.',
      'Social audit list published for objections at Grama Sachivalayam.',
      'Funds deposited directly via DBT into farmer bank accounts.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://karshak.ap.gov.in',
    applicationLink: 'https://ysrrythubharosa.ap.gov.in',
    helplineNumber: '1902 / 155251',
    status: 'Active',
    lastUpdated: new Date('2026-08-22'),
    lastVerified: new Date('2026-09-12'),
    sourceUrl: 'https://karshak.ap.gov.in',
  },

  // 18. AP - Jagananna Vidya Deevena (Fee Reimbursement)
  {
    schemeName: 'Jagananna Vidya Deevena (Post-Matric Fee Reimbursement AP)',
    schemeCode: 'AP-VIDYA-DEEVENA',
    description: 'Complete tuition fee reimbursement scheme for economically poor students pursuing ITI, Polytechnic, Degree, Engineering, Medicine, and Post-Graduation in Andhra Pradesh.',
    category: 'Education',
    governmentLevel: 'State',
    state: 'Andhra Pradesh',
    department: 'Social Welfare Department, Government of Andhra Pradesh',
    benefits: [
      '100% full tuition fee reimbursement credited on quarterly basis to mother’s bank account',
      'Covers government, aided, and recognized private universities/colleges across the state',
    ],
    benefitAmount: '100% Full Tuition Fee Reimbursement',
    eligibilityCriteria: {
      age: { min: 16, max: 30 },
      income: { max: 250000 },
      studentOnly: true,
      states: ['Andhra Pradesh'],
      educationLevels: ['12th Pass', 'Graduate', 'Post Graduate', 'All'],
    },
    ineligibilityCriteria: [
      'Students enrolled in deemed/private universities under management or NRI quota',
      'Students studying via distance education or correspondence courses',
      'Families owning four-wheeler vehicles or government employees',
    ],
    requiredDocuments: [
      'Student and Mother Aadhaar Cards',
      'White Ration Card / Rice Card',
      'College Allotment Order and Fee Structure Certificate',
      'Income Certificate issued by Revenue Tahsildar',
      'Mother’s active Bank Passbook',
    ],
    applicationProcess: [
      'College nodal officer registers student admission on Jnanabhumi portal.',
      'Student and mother perform biometric / Aadhaar OTP e-KYC authentication.',
      'Welfare Assistant at Village/Ward Secretariat verifies residence and economic status.',
      'Fee reimbursement disbursed quarterly directly to mother’s bank account.',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://jnanabhumi.ap.gov.in',
    applicationLink: 'https://jnanabhumi.ap.gov.in',
    helplineNumber: '08645-274025 / 1902',
    status: 'Active',
    lastUpdated: new Date('2026-08-14'),
    lastVerified: new Date('2026-09-09'),
    sourceUrl: 'https://jnanabhumi.ap.gov.in',
  },

  // ----------------------------------------------------
  // OTHER MAJOR STATE SCHEMES
  // ----------------------------------------------------

  // 19. Maharashtra - Mukhyamantri Majhi Ladki Bahin Yojana
  {
    schemeName: 'Mukhyamantri Majhi Ladki Bahin Yojana (Maharashtra)',
    schemeCode: 'MH-LADKI-BAHIN',
    description: 'Financial independence and nutritional support scheme providing ₹1,500 per month directly to underprivileged women aged 21 to 65 across Maharashtra.',
    category: 'Women & Child Welfare',
    governmentLevel: 'State',
    state: 'Maharashtra',
    department: 'Women and Child Development Department, Government of Maharashtra',
    benefits: [
      'Monthly direct cash assistance of ₹1,500 transferred to woman beneficiary bank account',
      'Empowers women to meet personal health, nutritional, and household needs independently',
    ],
    benefitAmount: '₹1,500 / Month (₹18,000 / Year)',
    eligibilityCriteria: {
      age: { min: 21, max: 65 },
      income: { max: 250000 },
      genders: ['Female'],
      states: ['Maharashtra'],
      rationCardCategories: ['Yellow', 'Orange', 'BPL', 'Any'],
    },
    ineligibilityCriteria: [
      'Beneficiaries whose family income exceeds ₹2.5 Lakhs per year',
      'Families having any income tax payer member or permanent government employee',
      'Beneficiaries receiving ₹1,500 or more under other government financial assistance schemes',
    ],
    requiredDocuments: [
      'Aadhaar Card of applicant',
      'Domicile Certificate of Maharashtra or 15-year old Ration Card/Voter ID',
      'Income Certificate (or Yellow/Orange Ration card)',
      'Aadhaar-seeded Bank Account Passbook',
      'Hamipatra (Self-declaration form)',
    ],
    applicationProcess: [
      'Apply online via Nari Shakti Doot Mobile App or portal ladkibahin.maharashtra.gov.in.',
      'Or apply through Setu Kendra, Anganwadi Sevika, or Gram Panchayat desk.',
      'District Collectorate verifies and approves eligible beneficiaries for monthly DBT.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://ladkibahin.maharashtra.gov.in',
    applicationLink: 'https://ladkibahin.maharashtra.gov.in',
    helplineNumber: '181 (Women Helpline)',
    status: 'Active',
    lastUpdated: new Date('2026-08-26'),
    lastVerified: new Date('2026-09-13'),
    sourceUrl: 'https://ladkibahin.maharashtra.gov.in',
  },

  // 20. Karnataka - Gruha Lakshmi Scheme
  {
    schemeName: 'Gruha Lakshmi Scheme (Karnataka)',
    schemeCode: 'KA-GRUHA-LAKSHMI',
    description: 'Provides ₹2,000 per month financial assistance to the woman head of every eligible household holding BPL, Antyodaya, or APL ration cards in Karnataka.',
    category: 'Women & Child Welfare',
    governmentLevel: 'State',
    state: 'Karnataka',
    department: 'Department of Women and Child Development, Karnataka',
    benefits: [
      'Monthly financial assistance of ₹2,000 credited via DBT to the woman head of the family',
      'Recognizes unpaid care work and enhances purchasing power of homemakers',
    ],
    benefitAmount: '₹2,000 / Month',
    eligibilityCriteria: {
      age: { min: 18, max: 95 },
      income: { max: 0 },
      genders: ['Female'],
      states: ['Karnataka'],
      maritalStatus: ['Married', 'Widow', 'Divorced', 'Single', 'Any'],
    },
    ineligibilityCriteria: [
      'Woman head or her husband paying Income Tax (IT) or Goods and Services Tax (GST)',
      'Woman head or husband employed in government service',
    ],
    requiredDocuments: [
      'Aadhaar Card of the woman head and her husband',
      'Karnataka Ration Card (BPL / AAY / APL card mentioning applicant as head)',
      'Aadhaar-linked Bank Account details',
      'Active mobile number',
    ],
    applicationProcess: [
      'Apply at Grama One, Karnataka One, Bangalore One centers, or Bapuji Seva Kendra.',
      'Or send an SMS appointment query to 8147500500.',
      'Biometric verification done at center, application submitted for DBT processing.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://sevasindhuservices.karnataka.gov.in',
    applicationLink: 'https://sevasindhuservices.karnataka.gov.in',
    helplineNumber: '1902 / 080-22279954',
    status: 'Active',
    lastUpdated: new Date('2026-08-15'),
    lastVerified: new Date('2026-09-10'),
    sourceUrl: 'https://sevasindhuservices.karnataka.gov.in',
  },

  // 21. Tamil Nadu - Pudhumai Penn Scheme
  {
    schemeName: 'Moovalur Ramamirtham Ammaiyar Pudhumai Penn Scheme (Tamil Nadu)',
    schemeCode: 'TN-PUDHUMAI-PENN',
    description: 'Provides financial assistance of ₹1,000 per month to female students who studied from Class 6 to 12 in Government schools till they complete undergraduate degree, diploma, or ITI courses.',
    category: 'Education',
    governmentLevel: 'State',
    state: 'Tamil Nadu',
    department: 'Department of Social Welfare and Women Empowerment, Tamil Nadu',
    benefits: [
      'Direct monthly cash transfer of ₹1,000 into student’s bank account throughout graduation period',
      'Incentivizes girl child higher education and prevents child marriages',
    ],
    benefitAmount: '₹1,000 / Month during graduation',
    eligibilityCriteria: {
      age: { min: 17, max: 25 },
      income: { max: 0 },
      genders: ['Female'],
      studentOnly: true,
      states: ['Tamil Nadu'],
    },
    ineligibilityCriteria: [
      'Girls who did not study continuously from Class 6 to 12 in Tamil Nadu Government schools',
      'Students pursuing distance education or open university courses',
    ],
    requiredDocuments: [
      'School Transfer Certificate (proving study in Govt school from Class 6-12)',
      'College Admission ID Card / Bonafide Certificate',
      'Aadhaar Card of student',
      'Student’s active Bank Passbook',
    ],
    applicationProcess: [
      'Colleges register eligible female students on the official Pudhumai Penn portal (pudhumaipenn.tn.gov.in).',
      'School Education EMIS verification verifies government school study record.',
      'Approved students receive monthly DBT assistance of ₹1,000.',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://pudhumaipenn.tn.gov.in',
    applicationLink: 'https://pudhumaipenn.tn.gov.in',
    helplineNumber: '181 / 044-25670875',
    status: 'Active',
    lastUpdated: new Date('2026-08-10'),
    lastVerified: new Date('2026-09-08'),
    sourceUrl: 'https://pudhumaipenn.tn.gov.in',
  },

  // 22. Telangana - Rythu Bharosa / Rythu Bandhu
  {
    schemeName: 'Rythu Bharosa (Telangana Farmer Investment Support Scheme)',
    schemeCode: 'TG-RYTHU-BHAROSA',
    description: 'Agricultural investment support scheme providing direct per-acre financial assistance to farmers before Kharif and Rabi seasons to purchase seeds, fertilizer, and farm inputs.',
    category: 'Agriculture',
    governmentLevel: 'State',
    state: 'Telangana',
    department: 'Department of Agriculture and Cooperation, Government of Telangana',
    benefits: [
      'Enhanced financial assistance of ₹15,000 per acre per year (₹7,500 per acre per season)',
      'Direct benefit transfer directly credited to farmer bank accounts through Dharani portal integration',
      'Free Rythu Bima life insurance of ₹5 Lakhs for farmer families',
    ],
    benefitAmount: '₹15,000 / Acre / Year',
    eligibilityCriteria: {
      age: { min: 18, max: 90 },
      income: { max: 0 },
      states: ['Telangana'],
      occupations: ['Farmer'],
      farmerSpecific: {
        landRequired: true,
        maxLandAcres: 0,
        farmerCategories: ['Any'],
      },
    },
    ineligibilityCriteria: [
      'Non-agricultural landholdings or real estate converted plots',
      'Absentee institutional landholders',
    ],
    requiredDocuments: [
      'Pattadar Passbook / Dharani Portal Land Record Number',
      'Aadhaar Card',
      'Bank Account Passbook (Aadhaar linked)',
    ],
    applicationProcess: [
      'Farmer land details are mapped automatically from Dharani portal records.',
      'Submit bank details to local Agriculture Extension Officer (AEO) if newly purchased.',
      'Amount credited directly before seasonal sowing starts.',
    ],
    applicationMode: 'Both',
    officialWebsite: 'https://rythubandhu.telangana.gov.in',
    applicationLink: 'https://dharani.telangana.gov.in',
    helplineNumber: '040-23383520 / 1800-425-4033',
    status: 'Active',
    lastUpdated: new Date('2026-08-20'),
    lastVerified: new Date('2026-09-11'),
    sourceUrl: 'https://rythubandhu.telangana.gov.in',
  },

  // 23. Uttar Pradesh - Mukhyamantri Kanya Sumangala Yojana
  {
    schemeName: 'Mukhyamantri Kanya Sumangala Yojana (Uttar Pradesh)',
    schemeCode: 'UP-KANYA-SUMANGALA',
    description: 'Conditional cash transfer scheme for girl children across 6 developmental milestones from birth, vaccination, school admissions to graduation, providing total financial security of ₹25,000.',
    category: 'Women & Child Welfare',
    governmentLevel: 'State',
    state: 'Uttar Pradesh',
    department: 'Women and Child Development Department, Uttar Pradesh',
    benefits: [
      'Total package of ₹25,000 disbursed across 6 stages (Birth: ₹5,000, Full Vaccination: ₹2,000, Class 1 Admission: ₹3,000, Class 6: ₹3,000, Class 9: ₹5,000, Graduation: ₹7,000)',
      'Ensures female child health, immunisation, and uninterrupted education',
    ],
    benefitAmount: '₹25,000 in 6 Milestones',
    eligibilityCriteria: {
      age: { min: 0, max: 22 },
      income: { max: 300000 },
      genders: ['Female'],
      states: ['Uttar Pradesh'],
    },
    ineligibilityCriteria: [
      'Families whose annual income exceeds ₹3,00,000',
      'Families with more than 2 children (except in case of twin girls)',
    ],
    requiredDocuments: [
      'Domicile Certificate of Uttar Pradesh',
      'Income Certificate (under ₹3 Lakh/year)',
      'Girl child birth certificate / school admission certificate',
      'Aadhaar Card of parents and child',
      'Joint bank account passbook',
    ],
    applicationProcess: [
      'Register online at mksy.up.gov.in.',
      'Select applicable stage/milestone (Stage 1 to Stage 6) and upload required certificates.',
      'Application verified by Block Development Officer / SDM.',
      'Sanctioned amount credited to parent/girl’s bank account.',
    ],
    applicationMode: 'Online',
    officialWebsite: 'https://mksy.up.gov.in',
    applicationLink: 'https://mksy.up.gov.in',
    helplineNumber: '181 / 0522-2287234',
    status: 'Active',
    lastUpdated: new Date('2026-08-16'),
    lastVerified: new Date('2026-09-07'),
    sourceUrl: 'https://mksy.up.gov.in',
  },
];

const sampleNotifications = [
  {
    title: 'PM-KISAN 19th Installment Released',
    message: 'The Government of India has credited the latest 4-monthly installment of ₹2,000 to all eligible farmer accounts with active e-KYC.',
    type: 'success',
    link: '/schemes/PM-KISAN',
    isGlobal: true,
  },
  {
    title: 'Andhra Pradesh Thalliki Vandanam Verification Open',
    message: 'Mothers of school-going children in AP can verify student attendance and bank seeding details at Village/Ward Sachivalayams.',
    type: 'info',
    link: '/schemes/AP-THALLIKI-VANDANAM',
    isGlobal: true,
  },
  {
    title: 'PMAY-Gramin New Target Allocation Approved',
    message: 'Central Government has approved additional 2 Crore rural houses under PMAY-G. Check your Gram Sabha eligibility list.',
    type: 'update',
    link: '/schemes/PMAY',
    isGlobal: true,
  },
  {
    title: 'National Scholarship Portal (NSP) Application Deadline Reminder',
    message: 'Applications for Pre-Matric and Post-Matric central scholarships close next month. Complete biometric e-KYC before deadline.',
    type: 'deadline',
    link: '/schemes/NMMSS',
    isGlobal: true,
  },
];

const additionalSchemes = require('./additionalSchemes');

const allSchemes = [...schemes, ...additionalSchemes];

module.exports = {
  statesAndDistricts,
  categories,
  schemes: allSchemes,
  sampleNotifications,
};
